---
sidebar: sidebar 
permalink: get-help.html 
keywords: get help, get support, knowledgebase, discord, phone, web, ticket, contact support, support ticket 
summary: NetApp fornece suporte para Trident de diversas maneiras. Opções de autoatendimento gratuitas e abrangentes estão disponíveis 24x7, como um canal no Discord. 
---
= Suporte
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp oferece suporte para Trident de diversas maneiras. Amplas opções de autoatendimento gratuitas estão disponíveis 24x7, como artigos da knowledgebase (KB) e um canal no Discord.



== Ciclo de vida do Trident

Trident oferece três níveis de suporte com base na sua versão. Consulte link:https://mysupport.netapp.com/site/info/version-support["NetApp suporte de versão de software para definições"^].

Suporte total:: Trident oferece suporte completo por doze meses a partir da data de lançamento.
Suporte limitado:: Trident oferece suporte limitado para os meses 13 a 24 a partir da data de lançamento.
Autoatendimento:: A documentação do Trident estará disponível para os meses 25 a 36 a partir da data de lançamento.


[cols="1, 1, 1, 1"]
|===


| Versão | Suporte total | Suporte limitado | Autoatendimento 


 a| 
link:https://docs.netapp.com/us-en/trident/index.html["25,10"^]
| Outubro 2026 | Outubro 2027 | Outubro 2028 


 a| 
link:https://docs.netapp.com/us-en/trident-2506/index.html["25,06"^]
| Junho de 2026 | Junho de 2027 | Junho de 2028 


 a| 
link:https://docs.netapp.com/us-en/trident-2502/index.html["25,02"^]
| Fevereiro de 2026 | Fevereiro de 2027 | Fevereiro de 2028 


 a| 
link:https://docs.netapp.com/us-en/trident-2410/index.html["24,10"^]
| -- | Outubro 2026 | Outubro 2027 


 a| 
link:https://docs.netapp.com/us-en/trident-2406/index.html["24,06"^]
| -- | Junho de 2026 | Junho de 2027 


 a| 
link:https://docs.netapp.com/us-en/trident-2402/index.html["24,02"^]
| -- | Fevereiro de 2026 | Fevereiro de 2027 


 a| 
link:https://docs.netapp.com/us-en/trident-2310/index.html["23,10"^]
| -- | -- | Outubro 2026 


 a| 
link:https://docs.netapp.com/us-en/trident-2307/index.html["23,07"^]
| -- | -- | Julho de 2026 


 a| 
link:https://docs.netapp.com/us-en/trident-2304/index.html["23,04"^]
| -- | -- | Abril de 2026 


 a| 
link:https://docs.netapp.com/us-en/trident-2301/index.html["23,01"^]
| -- | -- | Janeiro de 2026 
|===


== Autoatendimento

Para obter uma lista completa de artigos de resolução de problemas, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Trident_Kubernetes["NetApp Knowledgebase (login necessário)"^].



== Suporte da comunidade

Existe uma comunidade pública ativa de usuários de contêineres (incluindo desenvolvedores do Trident) em nosso link:https://discord.gg/NetApp["Canal do Discord"^]. Este é um ótimo lugar para fazer perguntas gerais sobre o projeto e discutir tópicos relacionados com colegas que compartilham os mesmos interesses.



== NetApp suporte técnico da NetApp

Para obter ajuda com Trident, crie um pacote de suporte usando `tridentctl logs -a -n trident` e envie-o para `NetApp Support <Getting Help>`.



== Para obter mais informações

* link:https://github.com/NetApp/trident["Recursos Trident"^]
* link:https://cloud.netapp.com/kubernetes-hub["Kubernetes Hub"^]

