---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: NetApp está constantemente aprimorando e melhorando seus produtos e serviços. Aqui estão alguns dos recursos, aprimoramentos e correções de bugs mais recentes na versão mais recente do Trident. 
---
= O que há de novo
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
As notas de versão fornecem informações sobre novos recursos, melhorias e correções de bugs na versão mais recente do NetApp Trident.


WARNING: O `tridentctl` binário para Linux fornecido no arquivo zip do instalador é a versão testada e suportada. Esteja ciente de que o `macos` binário fornecido na `/extras` parte do arquivo zip não é testado nem suportado.



== O que há de novo em 25.10

Saiba o que há de novo no Trident e Trident Protect, incluindo melhorias, correções e descontinuações.



=== Trident



==== Melhorias

* *Kubernetes*:
+
** Adicionado suporte para Snapshots de grupo de volume CSI com as APIs Kubernetes v1beta1 Volume Group Snapshot para os drivers ONTAP-NAS NFS e ONTAP-SAN-Economy, além do ONTAP-SAN (iSCSI e FC). Veja link:https://docs.netapp.com/us-en/trident/trident-use/vol-group-snapshots.html["Trabalhar com Snapshots de grupo de volume"^].
** Adicionado suporte para failover automático de cargas de trabalho com desanexação forçada de volumes para os drivers ONTAP-NAS e ONTAP-NAS-Economy (excluindo SMB em ambos os drivers NAS), e para os drivers ONTAP-SAN e ONTAP-SAN-Economy. Veja link:https://docs.netapp.com/us-en/trident/trident-reco/force-detach.html["Automatizando o failover de aplicações stateful com Trident"^].
** Concorrência de nós Trident aprimorada para maior escalabilidade nas operações de nós para volumes FCP.
** Adicionado suporte ONTAP AFX para o driver ONTAP NAS. Consulte link:https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html["Opções e exemplos de configuração do ONTAP NAS"^].
** Adicionado suporte para configurar solicitações e limites de recursos de CPU e memória para os contêineres Trident por meio do TridentOrchestrator CR e dos valores do Helm chart. (link:https://github.com/NetApp/trident/issues/1000["Problema #1000"], link:https://github.com/NetApp/trident/issues/927["Problema nº 927"], link:https://github.com/NetApp/trident/issues/853["Problema nº 853"], link:https://github.com/NetApp/trident/issues/592["Problema nº 592"], link:https://github.com/NetApp/trident/issues/110["Problema nº 110"]).
** Adicionado suporte FC para a personalidade ASAr2. Veja link:https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["Opções e exemplos de configuração do ONTAP SAN"^].
** Adicionada opção para servir métricas Prometheus com HTTPS, em vez de HTTP. Veja link:https://docs.netapp.com/us-en/trident/trident-use/monitor-trident.html["Monitorar Trident"^].
** Adicionada uma opção `--no-rename` ao importar um volume para manter o nome original, mas permitir que Trident gerencie o ciclo de vida do volume. Veja link:https://docs.netapp.com/us-en/trident/trident-use/vol-import.html["Importar volumes"^].
** A implantação do Trident agora é executada na classe de prioridade system-cluster-critical.


* Adicionada uma opção para o controlador Trident usar rede via helm, operator e tridentctl (link:https://github.com/NetApp/trident/issues/858["Problema nº 858"]).
* Adicionado suporte manual de QoS ao driver ANF, tornando-o pronto para produção no Trident 25.10; esse aprimoramento experimental foi introduzido no Trident 25.06.




==== Aprimoramentos experimentais


NOTE: Não deve ser utilizado em ambientes de produção.

* *[Prévia técnica]*: Adicionado suporte para simultaneidade para ONTAP-NAS (somente NFS) e ONTAP-SAN (NVMe para ONTAP 9 unificado), além da prévia técnica existente para o driver ONTAP-SAN (protocolos iSCSI e FCP no ONTAP 9 unificado).




==== Correções

* **Kubernetes**:
+
** Corrigida a inconsistência no nome do contêiner CSI node-driver-registrar, padronizando Linux DaemonSet para node-driver-registrar para corresponder ao Windows DaemonSet e à nomenclatura da imagem do contêiner.
** Corrigido um problema em que as políticas de exportação para qtrees legados não eram atualizadas corretamente.


* *Openshift*:
+
** Corrigido o problema de inicialização do pod do nó Trident em nós Windows no Openshift devido ao SCC ter allowHostDirVolumePlugin definido como falso (link:https://github.com/NetApp/trident/issues/950["Problema nº 950"]).


* Corrigido o problema em que o QPS da API do Kubernetes não estava sendo configurado via Helm (link:https://github.com/NetApp/trident/issues/975["Problema nº 975"]).
* Corrigida a impossibilidade de montar uma Persistent Volume Claim (PVC) baseada em um Snapshot de uma PVC de sistema de arquivos XFS baseado em NVMe no mesmo nó do Kubernetes.
* Corrigido o problema de alteração do UUID após reiniciar o host/Docker no modo NDVP, adicionando nomes de subsistema exclusivos/compartilhados por backend (por exemplo, netappdvp_subsystem).
* Corrigidos erros de montagem para volumes iSCSI durante a atualização do Trident de versões anteriores à 23.10 para 24.10 e superiores, resolvendo o problema de "SANType inválido".
* Corrigido o problema em que o estado do backend do Trident não estava sendo atualizado para online/offline sem reiniciar o controlador do Trident.
* Corrigida condição de corrida intermitente que causava redimensionamento lento do PVC.
* Corrigido o problema em que os snapshots não eram apagados em clone de volume em caso de falha na clonagem de volumes.
* Corrigida a falha ao remover o volume da fase de preparação quando o caminho do dispositivo era alterado pelo kernel.
* Corrigida a falha ao desestagiar o volume devido ao dispositivo LUKS já estar fechado.
* Corrigido problema em que operações de armazenamento lentas causavam erros ContextDeadline.
* Trident Operator aguardará o k8s-timeout configurável para verificar a versão do Trident.




=== Trident Protect

NetApp Trident Protect oferece recursos avançados de gerenciamento de dados de aplicativos que aprimoram a funcionalidade e a disponibilidade de aplicativos Kubernetes com estado, com suporte dos sistemas de armazenamento NetApp ONTAP e do provisionador de armazenamento NetApp Trident CSI.



==== Melhorias

* Adicionadas anotações para controlar os tempos limite de CR de snapshot para CRs de agendamento e backup:
+
** `protect.trident.netapp.io/snapshot-completion-timeout`
** `protect.trident.netapp.io/volume-snapshots-ready-to-use-timeout`
** `protect.trident.netapp.io/volume-snapshots-created-timeout`
+
Consulte link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-protect-apps.html["Anotações de backup e agendamento compatíveis"^].



* Adicionada uma anotação ao CR de agendamento para configurar o tempo limite de vinculação do PVC, que será usado pelo CR de backup: `protect.trident.netapp.io/pvc-bind-timeout-sec`. Veja link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-protect-apps.html["Anotações de backup e agendamento compatíveis"^].
* Listagens de backup e snapshot aprimoradas com um novo campo para indicar falhas no gancho de execução. `tridentctl-protect`




== Alterações em 25.06.2



=== Trident



==== Correções

* *Kubernetes*: corrigido um problema crítico em que dispositivos iSCSI incorretos eram detectados ao desanexar volumes de nós do Kubernetes.




== Alterações em 25.06.1



=== Trident


IMPORTANT: Para clientes que utilizam SolidFire, por favor, não atualizem para a versão 25.06.1 devido a um problema conhecido ao cancelar a publicação de volumes. A versão 25.06.2 será lançada em breve para corrigir esse problema.



==== Correções

* *Kubernetes*:
+
** Corrigido um problema em que os NQNs não eram verificados antes de serem desvinculados dos subsistemas.
** Corrigido um problema em que várias tentativas de fechar um dispositivo LUKS levavam a falhas ao desanexar volumes.
** Corrigida a desativação do volume iSCSI quando o caminho do dispositivo foi alterado desde a sua criação.
** Clonagem de volumes entre classes de armazenamento.


* *OpenShift*: corrigido um problema em que a preparação do nó iSCSI falhava com o OCP 4.19.
* Aumentou o tempo limite ao clonar um volume usando backends SolidFire (link:https://github.com/NetApp/trident/issues/1008["Problema nº 1008"]).




== Alterações em 25.06



=== Trident



==== Melhorias

* *Kubernetes*:
+
** Adicionado suporte para snapshots de grupos de volumes CSI com  `v1beta1`APIs Kubernetes de Snapshot de grupo de volumes para o driver ONTAP-SAN iSCSI. Consulte link:https://docs.netapp.com/us-en/trident/trident-use/vol-group-snapshots.html["Trabalhar com Snapshots de grupo de volume"^].
+

NOTE: VolumeGroupSnapshot é um recurso beta no Kubernetes com APIs beta. Kubernetes 1.32 é a versão mínima necessária para VolumeGroupSnapshot.

** Adicionado suporte para ONTAP ASA r2 para NVMe/TCP além de iSCSI. Veja link:https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["Opções e exemplos de configuração do ONTAP SAN"^].
** Adicionado suporte seguro a SMB para volumes ONTAP-NAS e ONTAP-NAS-Economy. Usuários e grupos do Active Directory agora podem ser usados com volumes SMB para maior segurança. Consulte link:https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-prep.html#enable-secure-smb["Ativar SMB seguro"^].
** Concorrência de nós Trident aprimorada para maior escalabilidade nas operações de nós para volumes iSCSI.
** Adicionado  `--allow-discards`ao abrir volumes LUKS para permitir comandos discard/TRIM para exigência de espaço.
** Desempenho aprimorado ao formatar volumes criptografados com LUKS.
** Limpeza aprimorada do LUKS para dispositivos com falha, mas parcialmente formatados.
** Idempotência aprimorada do nó Trident para conexão e desconexão de volumes NVMe.
** Adicionado  `internalID` campo à configuração de volume do Trident para o driver ONTAP-SAN-Economy.
** Adicionado suporte para replicação de volume com SnapMirror para backends NVMe. Consulte link:https://docs.netapp.com/us-en/trident/trident-use/vol-volume-replicate.html["Replicar volumes usando SnapMirror"^].






==== Aprimoramentos experimentais


NOTE: Não deve ser utilizado em ambientes de produção.

* [Prévia Técnica] Habilitada a execução simultânea de operações do controlador Trident por meio do recurso de sinalização  `--enable-concurrency`. Isso permite que as operações do controlador sejam executadas em paralelo, melhorando o desempenho para ambientes ocupados ou de grande porte.
+

NOTE: Este recurso é experimental e atualmente suporta fluxos de trabalho paralelos limitados com o driver ONTAP-SAN (protocolos iSCSI e FCP).

* [Prévia Técnica] Adicionado suporte manual a QOS com o driver ANF.




==== Correções

* *Kubernetes*:
+
** Corrigido um problema com o CSI NodeExpandVolume em que dispositivos multipath podiam ficar com tamanhos incongruentes quando os discos SCSI subjacentes não estavam disponíveis.
** Corrigida a falha ao limpar políticas de exportação duplicadas para os drivers ONTAP-NAS e ONTAP-NAS-Economy.
** Corrigido o problema em que os volumes GCNV usavam NFSv3 por padrão quando  `nfsMountOptions` não estava definido; agora, ambos os protocolos NFSv3 e NFSv4 são suportados. Se  `nfsMountOptions` não for fornecido, a versão de NFS padrão do host (NFSv3 ou NFSv4) será usada.
** Problema de implantação corrigido ao instalar Trident usando Kustomize (link:https://github.com/NetApp/trident/issues/831["Problema nº 831"]).
** Corrigidas as políticas de exportação ausentes para PVCs criados a partir de snapshots (link:https://github.com/NetApp/trident/issues/1016["Problema nº 1016"]).
** Corrigido o problema em que os tamanhos de volume do ANF não são alinhados automaticamente em incrementos de 1 GiB.
** Problema resolvido ao usar NFSv3 com Bottlerocket.


* Corrigido problema com volumes ONTAP-NAS-Economy que expandiam até 300 TB apesar de falhas no resize.
* Corrigido problema em que as operações de divisão de clones eram realizadas de forma síncrona ao usar a API REST do ONTAP.




==== Descontinuações:

* *Kubernetes*: versão mínima do Kubernetes suportada atualizada para v1.27.




=== Trident Protect

NetApp Trident Protect oferece recursos avançados de gerenciamento de dados de aplicativos que aprimoram a funcionalidade e a disponibilidade de aplicativos Kubernetes com estado, com suporte dos sistemas de armazenamento NetApp ONTAP e do provisionador de armazenamento NetApp Trident CSI.



==== Melhorias

* Tempos de restauração aprimorados, proporcionando a opção de fazer backups completos com mais frequência.
* Granularidade aprimorada da definição de aplicativos e restauração seletiva com filtragem por Group-Version-Kind (GVK).
* Ressincronização e replicação reversa eficientes ao usar AppMirrorRelationship (AMR) com NetApp SnapMirror, para evitar replicação completa de PVC.
* Adicionada a capacidade de usar a identidade do Pod do EKS para criar AppVault buckets, eliminando a necessidade de especificar um segredo com as credenciais do bucket para clusters EKS.
* Adicionada a capacidade de ignorar a restauração de rótulos e anotações no namespace de restauração, se necessário.
* AppMirrorRelationship (AMR) agora verificará a expansão do PVC de origem e realizará a expansão apropriada no PVC de destino, conforme necessário.




==== Correções

* Corrigido um bug em que os valores de anotação de snapshots anteriores estavam sendo aplicados a snapshots mais recentes. Todas as anotações de snapshots agora são aplicadas corretamente.
* Definida uma chave secreta para criptografia de movimentação de dados (Kopia / Restic) por padrão, caso não esteja definida.
* Adicionada validação aprimorada e mensagens de erro para a criação do appvault S3.
* AppMirrorRelationship (AMR) agora replica apenas PVs no estado Bound, para evitar tentativas falhas.
* Corrigido o problema em que erros eram exibidos ao obter AppVaultContent em um AppVault com um grande número de backups.
* KubeVirt VMSnapshots são excluídos das operações de restauração e failover para evitar falhas.
* Corrigido um problema no Kopia em que os snapshots estavam sendo removidos prematuramente devido à programação de retenção padrão do Kopia estar sobrescrevendo o que foi definido pelo usuário na programação.




== Alterações em 25.02.1



=== Trident



==== Correções

* *Kubernetes*:
+
** Corrigido um problema no trident-operator onde os nomes e versões das imagens sidecar eram preenchidos incorretamente ao usar um registro de imagens não padrão (link:https://github.com/NetApp/trident/issues/983["Problema nº 983"]).
** Corrigido o problema em que as sessões multipath não conseguiam se recuperar durante um giveback do ONTAP (link:https://github.com/NetApp/trident/issues/961["Problema nº 961"]).






== Alterações em 25.02

A partir da Trident 25.02, o resumo "Novidades" fornece detalhes sobre melhorias, correções e descontinuações para as versões do Trident e do Trident Protect.



=== Trident



==== Melhorias

* *Kubernetes*:
+
** Adicionado suporte para ONTAP ASA r2 para iSCSI.
** Adicionado suporte para desanexação forçada de volumes ONTAP-NAS durante cenários de desligamento não controlado do nó. Novos volumes ONTAP-NAS agora utilizarão políticas de exportação por volume gerenciadas pelo Trident. Fornecido um caminho de atualização para volumes existentes migrarem para o novo modelo de política de exportação ao cancelar a publicação, sem afetar as cargas de trabalho ativas.
** Adicionada a anotação cloneFromSnapshot.
** Adicionado suporte para clonagem de volumes entre namespaces.
** Recursos aprimorados de autorrecuperação iSCSI para iniciar novas varreduras por host, canal, alvo e ID de LUN exatos.
** Adicionado suporte para Kubernetes 1.32.


* *OpenShift*:
+
** Adicionado suporte para preparação automática de nós iSCSI para RHCOS em clusters ROSA.
** Adicionado suporte para OpenShift Virtualization para drivers ONTAP.


* Adicionado suporte a Fibre Channel no driver ONTAP-SAN.
* Adicionado suporte a NVMe LUKS.
* Alterado para imagem provisória para todas as imagens base.
* Adicionada descoberta e registro do estado de conexão iSCSI quando as sessões iSCSI deveriam estar conectadas, mas não estão (link:https://github.com/NetApp/trident/issues/961["Problema nº 961"]).
* Adicionado suporte para volumes SMB com o driver google-cloud-netapp-volumes.
* Adicionado suporte para permitir que volumes ONTAP ignorem a fila de recuperação ao serem excluídos.
* Adicionado suporte para substituir as imagens padrão usando SHAs em vez de tags.
* Adicionada a flag image-pull-secrets ao instalador tridentctl.




==== Correções

* *Kubernetes*:
+
** Corrigidos os endereços IP de nós ausentes nas políticas de exportação automática (link:https://github.com/NetApp/trident/issues/965["Problema nº 965"]).
** Corrigido o problema de políticas de exportação automáticas que mudavam prematuramente para a política por volume para ONTAP-NAS-Economy.
** Credenciais de configuração de backend corrigidas para suportar todas as partições ARN da AWS disponíveis (link:https://github.com/NetApp/trident/issues/913["Problema #913"]).
** Adicionada opção para desativar a reconciliação automática do configurador no operador Trident (link:https://github.com/NetApp/trident/issues/924["Problema nº 924"]).
** Adicionado securityContext para o contêiner csi-resizer (link:https://github.com/NetApp/trident/issues/976["Problema #976"]).






=== Trident Protect

NetApp Trident Protect oferece recursos avançados de gerenciamento de dados de aplicativos que aprimoram a funcionalidade e a disponibilidade de aplicativos Kubernetes com estado, com suporte dos sistemas de armazenamento NetApp ONTAP e do provisionador de armazenamento NetApp Trident CSI.



==== Melhorias

* Adicionado suporte de backup e restauração para KubeVirt / OpenShift VMs de Virtualização para ambos volumeMode: File e volumeMode: Block (armazenamento de dispositivo bruto). Esse suporte é compatível com todos os drivers Trident e aprimora os recursos de proteção existentes ao replicar o armazenamento usando NetApp SnapMirror com Trident Protect.
* Adicionada a capacidade de controlar o comportamento de congelamento no nível do aplicativo para ambientes Kubevirt.
* Adicionado suporte para configurar conexões proxy do AutoSupport.
* Adicionada a capacidade de definir um segredo para criptografia de data mover (Kopia / Restic).
* Adicionada a capacidade de executar manualmente um hook de execução.
* Adicionada a capacidade de configurar restrições de contexto de segurança (SCCs) durante a instalação do Trident Protect.
* Adicionado suporte para configurar nodeSelector durante a instalação do Trident Protect.
* Adicionado suporte para proxy de saída HTTP / HTTPS para objetos AppVault.
* Ampliado ResourceFilter para permitir a exclusão de recursos com escopo de cluster.
* Adicionada compatibilidade com o token de sessão da AWS nas credenciais do S3 AppVault.
* Adicionado suporte para coleta de recursos após a execução de hooks de pré-snapshot.




==== Correções

* Melhoramos a gestão de volumes temporários para pular a fila de recuperação de volumes do ONTAP.
* As anotações SCC agora são restauradas aos valores originais.
* Eficiência de restauração aprimorada com suporte para operações paralelas.
* Suporte aprimorado para tempos limite de gancho de execução para aplicações maiores.




== Alterações em 24.10.1



=== Melhorias

* *Kubernetes*: Adicionado suporte para Kubernetes 1.32.
* Adicionada descoberta e registro do estado de conexão iSCSI quando as sessões iSCSI deveriam estar conectadas, mas não estão (link:https://github.com/NetApp/trident/issues/961["Problema nº 961"]).




=== Correções

* Corrigidos os endereços IP de nós ausentes nas políticas de exportação automática (link:https://github.com/NetApp/trident/issues/965["Problema nº 965"]).
* Corrigido o problema de políticas de exportação automáticas que mudavam prematuramente para a política por volume para ONTAP-NAS-Economy.
* Dependências do Trident e do Trident-ASUP atualizadas para corrigir as vulnerabilidades CVE-2024-45337 e CVE-2024-45310.
* Removidos os logouts para portais não-CHAP intermitentemente não íntegros durante a autorrecuperação iSCSI (link:https://github.com/NetApp/trident/issues/961["Problema nº 961"]).




== Alterações em 24.10



=== Melhorias

* O driver do Google Cloud NetApp Volumes agora está disponível para o público em geral para volumes NFS e oferece suporte ao provisionamento com reconhecimento de zonas.
* A identidade de carga de trabalho do GCP será usada como identidade de nuvem para Google Cloud NetApp Volumes com GKE.
* Adicionado `formatOptions` parâmetro de configuração aos drivers ONTAP-SAN e ONTAP-SAN-Economy para permitir que os usuários especifiquem opções de formato LUN.
* Tamanho mínimo do volume do Azure NetApp Files reduzido para 50 GiB. Novo tamanho mínimo do Azure previsto para estar geralmente disponível em novembro.
* Adicionado `denyNewVolumePools` parâmetro de configuração para restringir os drivers ONTAP-NAS-Economy e ONTAP-SAN-Economy a pools Flexvol preexistentes.
* Adicionada detecção para a inclusão, remoção ou renomeação de agregados do SVM em todos os drivers ONTAP.
* Adicionado 18 MiB de sobrecarga aos LUNs LUKS para garantir que o tamanho do PVC relatado seja utilizável.
* Melhorado o tratamento de erros de estágio e desestágio de nós ONTAP-SAN e ONTAP-SAN-Economy para permitir que o desestágio remova dispositivos após uma falha de estágio.
* Adicionado um gerador de funções personalizadas que permite aos clientes criar uma função minimalista para Trident no ONTAP.
* Adicionado registro adicional para solução de problemas `lsscsi` (link:https://github.com/NetApp/trident/issues/792["Problema nº 792"]).




==== Kubernetes

* Adicionados novos recursos do Trident para fluxos de trabalho nativos do Kubernetes:
+
** Proteção de dados
** Migração de dados
** Recuperação de desastres
** Mobilidade de aplicativos
+
link:./trident-protect/learn-about-trident-protect.html["Saiba mais sobre Trident Protect"].



* Adicionada uma nova opção `--k8s-api-qps` aos instaladores para definir o valor de QPS usado pelo Trident para se comunicar com o servidor da API do Kubernetes.
* Adicionada  `--node-prep`flag aos instaladores para gerenciamento automático das dependências do protocolo de storage nos nós do cluster Kubernetes. Testada e verificada a compatibilidade com Amazon Linux 2023 protocolo de storage iSCSI
* Adicionado suporte para desanexação forçada para volumes ONTAP-NAS-Economy durante cenários de desligamento não controlado do nó.
* Novos volumes NFS ONTAP-NAS-Economy usarão políticas de exportação por qtree ao usar a opção de backend  `autoExportPolicy`. As qtrees só serão mapeadas para políticas de exportação restritivas de nó no momento da publicação para melhorar o controle de acesso e a segurança. As qtrees existentes serão migradas para o novo modelo de política de exportação quando Trident despublicar o volume de todos os nós, para fazer isso sem impactar as cargas de trabalho ativas.
* Adicionado suporte para Kubernetes 1.31.




==== Aprimoramentos experimentais

* Adicionada prévia técnica para suporte a Fibre Channel no driver ONTAP-SAN.




=== Correções

* *Kubernetes*:
+
** Corrigido o webhook de admissão do Rancher que impedia instalações do Trident Helm (link:https://github.com/NetApp/trident/issues/839["Problema nº 839"]).
** Chave de afinidade fixa nos valores do gráfico Helm (link:https://github.com/NetApp/trident/issues/898["Problema nº 898"]).
** Corrigido tridentControllerPluginNodeSelector/tridentNodePluginNodeSelector não funcionará com o valor "true" (link:https://github.com/NetApp/trident/issues/899["Problema nº 899"]).
** Instantâneos efêmeros excluídos criados durante a clonagem (link:https://github.com/NetApp/trident/issues/901["Problema nº 901"]).


* Adicionado suporte para Windows Server 2019.
* Corrigido `go mod tidy` no repositório Trident (link:https://github.com/NetApp/trident/issues/767["Problema #767"]).




=== Descontinuações

* *Kubernetes:*
+
** Versão mínima do Kubernetes suportada atualizada para 1.25.
** Removido o suporte para POD Security Policy.






=== Rebranding do produto

A partir da versão 24.10, Astra Trident passou a se chamar Trident (NetApp Trident). Essa mudança de nome não afeta nenhum recurso, plataforma suportada ou interoperabilidade do Trident.



== Alterações em 24.06



=== Melhorias

* **IMPORTANTE**: O `limitVolumeSize` parâmetro agora limita os tamanhos de qtree/LUN nos drivers econômicos do ONTAP. Use o novo  `limitVolumePoolSize` parâmetro para controlar os tamanhos de Flexvol nesses drivers. (link:https://github.com/NetApp/trident/issues/341["Problema nº 341"]).
* Adicionada a capacidade de autorrecuperação iSCSI para iniciar varreduras SCSI pelo ID exato do LUN se igroups obsoletos estiverem em uso (link:https://github.com/NetApp/trident/issues/883["Problema nº 883"]).
* Adicionado suporte para operações de clone de volume e redimensionamento serem permitidas mesmo quando o backend estiver em modo suspenso.
* Adicionada a capacidade de as configurações de log definidas pelo usuário para o controlador Trident serem propagadas para os pods de nó do Trident.
* Adicionado suporte no Trident para usar REST por padrão em vez de ONTAPI (ZAPI) para versões do ONTAP 9.15.1 e posteriores.
* Adicionado suporte para nomes de volumes personalizados e metadados nos backends de armazenamento ONTAP para novos volumes persistentes.
* Aprimorado o driver  `azure-netapp-files` (ANF) para habilitar automaticamente o diretório de snapshots por padrão quando as opções de montagem NFS estiverem definidas para usar a versão de NFS 4.x.
* Adicionado suporte ao Bottlerocket para volumes NFS.
* Adicionado suporte de pré-visualização técnica para Google Cloud NetApp Volumes.




==== Kubernetes

* Adicionado suporte para Kubernetes 1.30.
* Adicionada capacidade para Trident DaemonSet limpar montarias de zumbis e arquivos residuais de rastreamento na inicialização (link:https://github.com/NetApp/trident/issues/883["Problema nº 883"]).
* Adicionada anotação PVC `trident.netapp.io/luksEncryption` para importação dinâmica de volumes LUKS (link:https://github.com/NetApp/trident/issues/849["Problema #849"]).
* Adicionada a capacidade de reconhecimento de topologia ao driver ANF.
* Adicionado suporte para nós do Windows Server 2022.




=== Correções

* Corrigidas falhas na instalação do Trident devido a transações obsoletas.
* Corrigido o tridentctl para ignorar mensagens de aviso do Kubernetes (link:https://github.com/NetApp/trident/issues/892["Problema #892"]).
* Alterada a prioridade do controlador Trident `SecurityContextConstraint` para `0` (link:https://github.com/NetApp/trident/issues/887["Problema nº 887"]).
* Os drivers ONTAP agora aceitam tamanhos de volume abaixo de 20 MiB (link:https://github.com/NetApp/trident/issues/885["Problema[#885"]).
* Correção no Trident para evitar a redução de volumes FlexVol durante a operação de redimensionamento para o driver ONTAP-SAN.
* Corrigida a falha na importação de volumes ANF com NFS v4.1.




== Alterações em 24.02



=== Melhorias

* Adicionado suporte para Cloud Identity.
+
** AKS com ANF - Azure Workload Identity será usado como identidade na nuvem.
** EKS com FSxN - a função AWS IAM será usada como identidade na nuvem.


* Adicionado suporte para instalar Trident como um complemento no cluster EKS a partir do console do EKS.
* Adicionada a capacidade de configurar e desativar a autorrecuperação iSCSI (link:https://github.com/NetApp/trident/issues/864["Problema nº 864"]).
* Adicionada personalidade Amazon FSx aos drivers ONTAP para permitir a integração com AWS IAM e SecretsManager, e para permitir que Trident exclua volumes FSx com backups (link:https://github.com/NetApp/trident/issues/453["Problema #453"]).




==== Kubernetes

* Adicionado suporte para Kubernetes 1.29.




=== Correções

* Mensagens de aviso do ACP corrigidas, quando o ACP não está ativado (link:https://github.com/NetApp/trident/issues/866["Problema nº 866"]).
* Adicionado um atraso de 10 segundos antes de realizar a divisão de clones durante a exclusão de snapshot para ONTAP drivers, quando um clone está associado ao snapshot.




=== Descontinuações

* Removida a estrutura de atestação in-toto dos manifestos de imagem multiplataforma.




== Alterações em 23.10



=== Correções

* Corrigida a expansão de volume se um novo tamanho solicitado for menor que o tamanho total do volume para drivers de armazenamento ontap-nas e ontap-nas-flexgroup (link:https://github.com/NetApp/trident/issues/834["Problema nº 834"^]).
* Tamanho de volume fixo para exibir apenas o tamanho utilizável do volume durante a importação para os drivers de armazenamento ontap-nas e ontap-nas-flexgroup (link:https://github.com/NetApp/trident/issues/722["Problema nº 722"^]).
* Correção na conversão de nomes de FlexVol para ONTAP-NAS-Economy.
* Corrigido o problema de inicialização do Trident em um nó Windows quando o nó é reinicializado.




=== Melhorias



==== Kubernetes

Adicionado suporte para Kubernetes 1.28.



==== Trident

* Adicionado suporte para o uso de Azure Managed Identities (AMI) com o driver de armazenamento azure-netapp-files.
* Adicionado suporte para NVMe over TCP para o driver ONTAP-SAN.
* Adicionada a capacidade de pausar o provisionamento de um volume quando o backend for definido como estado suspenso pelo usuário (link:https://github.com/NetApp/trident/issues/558["Problema nº 558"^]).




== Alterações em 23.07.1

*Kubernetes:* Corrigida a exclusão do daemonset para suportar atualizações sem tempo de inatividade (link:https://github.com/NetApp/trident/issues/740["Problema nº 740"^]).



== Alterações em 23.07



=== Correções



==== Kubernetes

* Correção na atualização do Trident para ignorar pods antigos presos no estado de término (link:https://github.com/NetApp/trident/issues/740["Problema nº 740"^]).
* Adicionada tolerância à definição "transient-trident-version-pod" (link:https://github.com/NetApp/trident/issues/795["Problema #795"^]).




==== Trident

* Corrigidas as solicitações ONTAPI (ZAPI) para garantir que os números de série do LUN sejam consultados ao obter os atributos do LUN, a fim de identificar e corrigir dispositivos iSCSI fantasmas durante as operações de preparação de nós.
* Correção no tratamento de erros no código do driver de armazenamento (link:https://github.com/NetApp/trident/issues/816["Problema nº 816"^]).
* Correção no redimensionamento de cotas ao usar drivers ONTAP com use-rest=true.
* Correção na criação de clone de LUN em ontap-san-economy.
* Reverter o campo de informações de publicação de `rawDevicePath` para `devicePath`; adicionada lógica para preencher e recuperar (em alguns casos) `devicePath` campo.




=== Melhorias



==== Kubernetes

* Adicionado suporte para importação de snapshots pré-provisionados.
* Implantação minimizada e permissões do daemonset linux (link:https://github.com/NetApp/trident/issues/817["Problema nº 817"^]).




==== Trident

* Não é mais exibido o campo de estado para volumes e snapshots "online".
* Atualiza o estado do backend se o ONTAP backend estiver offline (link:https://github.com/NetApp/trident/issues/801["Problemas #801"^], link:https://github.com/NetApp/trident/issues/543["#543"^]).
* O número de série do LUN é sempre recuperado e publicado durante o ControllerVolumePublish workflow.
* Adicionada lógica adicional para verificar o número de série e o tamanho do dispositivo iSCSI multipath.
* Verificação adicional para volumes iSCSI para garantir que o dispositivo multipath correto esteja descompactado.




==== Aprimoramento experimental

Adicionado suporte em prévia técnica para NVMe over TCP para o driver ONTAP-SAN.



==== Documentação

Muitas melhorias de organização e formatação foram feitas.



=== Descontinuações



==== Kubernetes

* Removido o suporte para snapshots v1beta1.
* Removido o suporte para volumes e classes de armazenamento pré-CSI.
* Versão mínima do Kubernetes suportada atualizada para 1.22.




== Alterações em 23.04


IMPORTANT: O recurso de desanexação forçada de volumes ONTAP-SAN-* é compatível apenas com versões do Kubernetes que possuem o recurso de desligamento não gradual do nó ativado. A desanexação forçada deve ser habilitada durante a instalação usando a  `--enable-force-detach` flag do instalador Trident.



=== Correções

* Corrigido o Trident Operator para usar IPv6 localhost para instalação quando especificado em spec.
* Corrigidas as permissões da função de cluster do operador Trident para estarem sincronizadas com as permissões do pacote (link:https://github.com/NetApp/trident/issues/799["Problema nº 799"^]).
* Corrigido problema com a anexação de volume de bloco bruto em vários nós no modo RWX.
* Correção do suporte à clonagem de FlexGroup e importação de volumes SMB.
* Corrigido problema em que o controlador Trident não conseguia ser desligado imediatamente (link:https://github.com/NetApp/trident/issues/811["Problema nº 811"]).
* Adicionada correção para listar todos os nomes de igroup associados a uma LUN especificada provisionada com drivers ontap-san-*.
* Adicionada uma correção para permitir que processos externos sejam executados até a conclusão.
* Erro de compilação corrigido para a arquitetura s390 (link:https://github.com/NetApp/trident/issues/537["Problema #537"]).
* Corrigido o nível de registro incorreto durante as operações de montagem de volume (link:https://github.com/NetApp/trident/issues/781["Problema #781"]).
* Corrigido erro potencial de asserção de tipo (link:https://github.com/NetApp/trident/issues/802["Problema #802"]).




=== Melhorias

* Kubernetes:
+
** Adicionado suporte para Kubernetes 1.27.
** Adicionado suporte para importação de volumes LUKS.
** Adicionada compatibilidade com o modo de acesso ReadWriteOncePod em PVC.
** Adicionado suporte para desanexação forçada para volumes ONTAP-SAN-* durante cenários de desligamento não controlado do nó.
** Todos os volumes ONTAP-SAN-* agora usarão igroups por nó. Os LUNs serão mapeados para igroups somente enquanto estiverem ativamente publicados nesses nós para melhorar nossa postura de segurança. Os volumes existentes serão migrados para o novo esquema de igroups de forma oportunista quando Trident determinar que é seguro fazê-lo sem impactar as cargas de trabalho ativas (link:https://github.com/NetApp/trident/issues/758["Problema nº 758"]).
** Segurança do Trident aprimorada ao limpar igroups gerenciados pelo Trident e não utilizados dos backends ONTAP-SAN-*.


* Adicionado suporte para volumes SMB com Amazon FSx aos drivers de armazenamento ontap-nas-economy e ontap-nas-flexgroup.
* Adicionado suporte para compartilhamentos SMB com os drivers de armazenamento ontap-nas, ontap-nas-economy e ontap-nas-flexgroup.
* Adicionado suporte para nós arm64 (link:https://github.com/NetApp/trident/issues/732["Problema nº 732"]).
* Procedimento de desligamento do Trident aprimorado, desativando primeiro os servidores de API (link:https://github.com/NetApp/trident/issues/811["Problema nº 811"]).
* Adicionada compatibilidade com compilação multiplataforma para hosts Windows e arm64 ao Makefile; consulte BUILD.md.




=== Descontinuações

**Kubernetes:** Grupos de interfaces com escopo de backend não serão mais criados ao configurar os drivers ontap-san e ontap-san-economy (link:https://github.com/NetApp/trident/issues/758["Problema nº 758"]).



== Alterações em 23.01.1



=== Correções

* Corrigido o Trident Operator para usar IPv6 localhost para instalação quando especificado em spec.
* Corrigidas as permissões da função de cluster do operador Trident para estarem sincronizadas com as permissões do bundle link:https://github.com/NetApp/trident/issues/799["Problema nº 799"^].
* Adicionada uma correção para permitir que processos externos sejam executados até a conclusão.
* Corrigido problema com a anexação de volume de bloco bruto em vários nós no modo RWX.
* Correção do suporte à clonagem de FlexGroup e importação de volumes SMB.




== Alterações em 23.01


IMPORTANT: Kubernetes 1.27 agora é compatível com Trident. Atualize Trident antes de atualizar Kubernetes.



=== Correções

* Kubernetes: adicionadas opções para excluir a criação de Pod Security Policy para corrigir instalações do Trident via Helm (link:https://github.com/NetApp/trident/issues/794["Problemas nº 783, nº 794"^]).




=== Melhorias

.Kubernetes
* Adicionado suporte para Kubernetes 1.26.
* Melhoria geral da utilização de recursos do Trident (link:https://github.com/NetApp/trident/issues/757["Problema nº 757"^]).
* Adicionada automação para detectar e corrigir sessões iSCSI interrompidas ou obsoletas em nós de host.
* Adicionado suporte para expandir volumes criptografados com LUKS.
* Kubernetes: Adicionado suporte à rotação de credenciais para volumes criptografados com LUKS.


.Trident
* Adicionado suporte para volumes SMB com Amazon FSx for NetApp ONTAP ao driver de armazenamento ontap-nas.
* Adicionado suporte para permissões NTFS ao usar volumes SMB.
* Adicionado suporte para pools de armazenamento para volumes do GCP com nível de serviço CVS.
* Adicionado suporte ao uso opcional de flexgroupAggregateList ao criar FlexGroups com o driver de armazenamento ontap-nas-flexgroup.
* Desempenho aprimorado para o driver de armazenamento ontap-nas-economy ao gerenciar vários volumes FlexVol
* Ativadas as atualizações do dataLIF para todos os drivers de armazenamento ONTAP NAS.
* Atualizada a convenção de nomenclatura de implantação do Trident e DaemonSet para refletir o sistema operacional do nó host.




=== Descontinuações

* Kubernetes: versão mínima do Kubernetes suportada atualizada para 1.21.
* Não é mais necessário especificar DataLIFs ao configurar  `ontap-san` ou  `ontap-san-economy`drivers.




== Alterações em 22.10

*Você deve ler as seguintes informações críticas antes de atualizar para Trident 22.10.*

[WARNING]
.<strong>Informações críticas sobre Trident 22.10</strong>
====
* Kubernetes 1.25 agora é compatível com Trident. Você deve atualizar o Trident para 22.10 antes de atualizar para o Kubernetes 1.25.
* Trident agora impõe rigorosamente o uso da configuração de multipath em ambientes SAN, com um valor recomendado de  `find_multipaths: no` no arquivo multipath.conf.
+
O uso de configuração sem multipath ou o uso de  `find_multipaths: yes` ou  `find_multipaths: smart` valor no arquivo multipath.conf resultará em falhas de montagem. Trident recomenda o uso de  `find_multipaths: no` desde o lançamento 21.07.



====


=== Correções

* Corrigido problema específico do backend ONTAP criado usando  `credentials` campo que não entrava em funcionamento durante a atualização 22.07.0 (link:https://github.com/NetApp/trident/issues/759["Problema #759"^]).
* **Docker:** Corrigido um problema que impedia o plugin de volume do Docker de iniciar em alguns ambientes (link:https://github.com/NetApp/trident/issues/548["Problema #548"^] e link:https://github.com/NetApp/trident/issues/760["Problema #760"^]).
* Corrigido problema de SLM específico para backends SAN ONTAP para garantir que apenas um subconjunto de dataLIFs pertencentes a nós de relatório sejam publicados.
* Corrigido problema de desempenho em que varreduras desnecessárias de LUNs iSCSI ocorriam ao conectar um volume.
* Removidas as tentativas granulares dentro do fluxo de trabalho iSCSI do Trident para falhar rapidamente e reduzir os intervalos de repetição externa.
* Corrigido um problema em que um erro era retornado ao limpar um dispositivo iSCSI quando o dispositivo multipath correspondente já havia sido limpo.




=== Melhorias

* Kubernetes:
+
** Adicionado suporte para Kubernetes 1.25. Você deve atualizar Trident para 22.10 antes de atualizar para Kubernetes 1.25.
** Adicionado um ServiceAccount, ClusterRole e ClusterRoleBinding separados para a implantação do Trident e DaemonSet para permitir futuras melhorias de permissões.
** Adicionado suporte para link:https://docs.netapp.com/us-en/trident/trident-use/volume-share.html["compartilhamento de volumes entre namespaces"].


* Todos os drivers de armazenamento Trident `ontap-*` agora funcionam com a API REST do ONTAP.
* Adicionado novo operador yaml (`bundle_post_1_25.yaml`) sem um `PodSecurityPolicy` para suportar Kubernetes 1.25.
* Adicionado link:https://docs.netapp.com/us-en/trident/trident-reco/security-luks.html["suporte para volumes criptografados com LUKS"] para  `ontap-san` e  `ontap-san-economy` drivers de armazenamento.
* Adicionado suporte para nós do Windows Server 2019.
* Adicionado link:https://docs.netapp.com/us-en/trident/trident-use/anf.html["Suporte para volumes SMB em nós Windows"] através do  `azure-netapp-files` driver de armazenamento.
* A detecção automática de switchover MetroCluster para drivers ONTAP agora está geralmente disponível.




=== Descontinuações

* **Kubernetes:** versão mínima do Kubernetes suportada atualizada para 1.20.
* Driver Astra Data Store (ADS) removido.
* Removido suporte para `yes` e `smart` opções para `find_multipaths` ao configurar multipath de nó de trabalho para iSCSI.




== Alterações em 22.07



=== Correções

**Kubernetes**

* Corrigido problema no tratamento de valores booleanos e numéricos para o seletor de nós ao configurar Trident com Helm ou Trident Operator. (link:https://github.com/NetApp/trident/issues/700["GitHub issue nº 700"^])
* Corrigido problema no tratamento de erros em caminhos não-CHAP, de forma que o kubelet tente novamente em caso de falha. link:https://github.com/NetApp/trident/issues/736["GitHub issue nº 736"^])




=== Melhorias

* Transição de k8s.gcr.io para registry.k8s.io como registro padrão para imagens CSI
* Os volumes ONTAP-SAN agora usarão igroups por nó e mapearão LUNs para igroups somente enquanto estiverem ativamente publicados nesses nós para aprimorar nossa postura de segurança. Os volumes existentes serão migrados para o novo esquema de igroups de forma oportunista quando o Trident determinar que é seguro fazê-lo sem impactar as cargas de trabalho ativas.
* Incluído um ResourceQuota nas instalações do Trident para garantir que o Trident DaemonSet seja agendado quando o consumo de PriorityClass for limitado por padrão.
* Adicionado suporte para Recursos de Rede ao driver do Azure NetApp Files. (link:https://github.com/NetApp/trident/issues/717["GitHub issue nº 717"^])
* Adicionada detecção automática de switchover MetroCluster (tech preview) aos drivers ONTAP. (link:https://github.com/NetApp/trident/issues/228["GitHub issue nº 228"^])




=== Descontinuações

* **Kubernetes:** versão mínima do Kubernetes suportada atualizada para 1.19.
* A configuração do backend não permite mais múltiplos tipos de autenticação em uma única configuração.




=== Remoções

* O driver AWS CVS (obsoleto desde 22.04) foi removido.
* Kubernetes
+
** Removida a capacidade SYS_ADMIN desnecessária dos pods dos nós.
** Reduz o nodeprep a informações simples do host e descoberta ativa de serviços para realizar uma confirmação da melhor forma possível de que os serviços NFS/iSCSI estão disponíveis nos nós de trabalho.






=== Documentação

Uma nova link:https://docs.netapp.com/us-en/trident/trident-reference/pod-security.html["Padrões de segurança do Pod"] seção (PSS) foi adicionada detalhando as permissões habilitadas pelo Trident na instalação.



== Alterações em 22.04

NetApp está continuamente aprimorando e melhorando seus produtos e serviços. Aqui estão alguns dos recursos mais recentes em Trident. Para versões anteriores, consulte  https://docs.netapp.com/us-en/trident/earlier-versions.html["Versões anteriores da documentação"].


IMPORTANT: Se você estiver atualizando de qualquer versão anterior do Trident e usar o Azure NetApp Files, o ``location`` parâmetro de configuração agora é um campo obrigatório e único.



=== Correções

* Melhoria na análise dos nomes dos iniciadores iSCSI. (link:https://github.com/NetApp/trident/issues/681["GitHub issue nº 681"^])
* Corrigido problema em que os parâmetros da classe de armazenamento CSI não eram permitidos. (link:https://github.com/NetApp/trident/issues/598["Issue do GitHub #598"^])
* Correção de declaração de chave duplicada no Trident CRD. (link:https://github.com/NetApp/trident/issues/671["Problema do GitHub #671"^])
* Corrigidos os registros de Snapshot CSI imprecisos. (link:https://github.com/NetApp/trident/issues/629["Problema do GitHub #629"^]))
* Problema corrigido com a remoção da publicação de volumes em nós excluídos. (link:https://github.com/NetApp/trident/issues/691["GitHub issue nº 691"^])
* Adicionada a funcionalidade de tratamento de inconsistências do sistema de arquivos em dispositivos de bloco. (link:https://github.com/NetApp/trident/issues/656["Problema do GitHub #656"^])
* Corrigido problema ao obter imagens de auto-support ao definir o  `imageRegistry` flag durante a instalação. (link:https://github.com/NetApp/trident/issues/715["Problema do GitHub #715"^])
* Corrigido um problema em que o driver do Azure NetApp Files não conseguia clonar um volume com várias regras de exportação.




=== Melhorias

* As conexões de entrada para os endpoints seguros do Trident agora exigem no mínimo TLS 1.3. (link:https://github.com/NetApp/trident/issues/698["Problema do GitHub #698"^])
* Trident agora adiciona cabeçalhos HSTS às respostas de seus endpoints seguros.
* Trident agora tenta habilitar automaticamente o recurso de permissões unix do Azure NetApp Files.
* *Kubernetes*: O daemonset Trident agora é executado na classe de prioridade system-node-critical. (link:https://github.com/NetApp/trident/issues/694["Problema do GitHub #694"^])




=== Remoções

O driver E-Series (desativado desde 20.07) foi removido.



== Alterações em 22.01.1



=== Correções

* Problema corrigido com a remoção da publicação de volumes em nós excluídos. (link:https://github.com/NetApp/trident/issues/691["GitHub issue nº 691"])
* Corrigido o erro que causava pânico ao acessar campos nulos para espaço agregado nas respostas da API ONTAP.




== Alterações em 22.01.0



=== Correções

* *Kubernetes:* Aumente o tempo de repetição de backoff do registro de nós para clusters grandes.
* Corrigido um problema em que o driver azure-netapp-files podia ser confundido por múltiplos recursos com o mesmo nome.
* Agora, os DataLIFs IPv6 do SAN ONTAP funcionam se especificados entre colchetes.
* Corrigido problema em que a tentativa de importar um volume já importado retornava EOF, deixando o PVC em estado pendente. (link:https://github.com/NetApp/trident/issues/489["Problema do GitHub #489"])
* Corrigido problema em que o desempenho do Trident ficava mais lento quando mais de 32 snapshots eram criados em um SolidFire volume.
* Substituído SHA-1 por SHA-256 na criação do certificado SSL.
* Corrigido o driver do Azure NetApp Files para permitir nomes de recursos duplicados e limitar as operações a um único local.
* Corrigido o driver do Azure NetApp Files para permitir nomes de recursos duplicados e limitar as operações a um único local.




=== Melhorias

* Aprimoramentos do Kubernetes:
+
** Adicionado suporte para Kubernetes 1.23.
** Adicionar opções de agendamento para Trident pods quando instalados via Trident Operator ou Helm. (link:https://github.com/NetApp/trident/issues/651["GitHub issue nº 651"^])


* Permitir volumes entre regiões no driver do GCP. (link:https://github.com/NetApp/trident/issues/633["GitHub issue nº 633"^])
* Adicionado suporte para a opção 'unixPermissions' aos volumes do Azure NetApp Files. (link:https://github.com/NetApp/trident/issues/666["GitHub issue nº 666"^])




=== Descontinuações

A interface REST do Trident só pode escutar e atender em endereços 127.0.0.1 ou [::1]



== Alterações em 21.10.1


WARNING: A versão v21.10.0 apresenta um problema que pode colocar o controlador Trident em um estado CrashLoopBackOff quando um nó é removido e depois adicionado novamente ao cluster Kubernetes. Esse problema foi corrigido na v21.10.1 (GitHub issue 669).



=== Correções

* Corrigida uma possível condição de corrida ao importar um volume em um backend CVS do GCP, resultando em falha na importação.
* Corrigido um problema que pode colocar o controlador Trident em um estado CrashLoopBackOff quando um nó é removido e depois adicionado novamente ao cluster Kubernetes (GitHub issue 669).
* Corrigido o problema em que as SVMs não eram mais detectadas se nenhum nome de SVM fosse especificado (GitHub issue 612).




== Alterações em 21.10.0



=== Correções

* Corrigido o problema em que clones de volumes XFS não podiam ser montados no mesmo nó que o volume de origem (GitHub issue 514).
* Corrigido o problema em que Trident registrava um erro fatal ao ser desligado (GitHub issue 597).
* Correções relacionadas a Kubernetes:
+
** Retorne o espaço usado de um volume como o mínimo restoreSize ao criar snapshots com  `ontap-nas` e  `ontap-nas-flexgroup` drivers (GitHub issue 645).
** Corrigido o problema em que `Failed to expand filesystem` erro era registrado após o redimensionamento do volume (GitHub issue 560).
** Corrigido problema em que um pod podia ficar preso em  `Terminating` state (GitHub issue 572).
** Corrigido o caso em que um `ontap-san-economy` FlexVol poderia estar cheio de LUNs de snapshot (GitHub issue 533).
** Corrigido problema com instalador YAML personalizado com imagem diferente (GitHub issue 613).
** Cálculo corrigido do tamanho do instantâneo (GitHub issue 611).
** Corrigido o problema em que todos os instaladores do Trident podiam identificar o Kubernetes puro como OpenShift (GitHub issue 639).
** Corrigido o operador Trident para interromper a reconciliação se o servidor da API do Kubernetes estiver inacessível (GitHub issue 599).






=== Melhorias

* Adicionado suporte para a opção  `unixPermissions` em volumes de desempenho do GCP-CVS.
* Adicionado suporte para volumes CVS otimizados para escala no GCP na faixa de 600 GiB a 1 TiB.
* Melhorias relacionadas ao Kubernetes:
+
** Adicionado suporte para Kubernetes 1.22.
** Habilitamos o operador Trident e o gráfico Helm para funcionar com o Kubernetes 1.22 (GitHub issue 628).
** Adicionada imagem do operador ao  `tridentctl` comando de imagens (GitHub issue 570).






=== Aprimoramentos experimentais

* Adicionado suporte para replicação de volumes no driver `ontap-san`.
* Adicionado suporte *prévia técnica* REST para os  `ontap-nas-flexgroup`, `ontap-san`, e  `ontap-nas-economy` drivers.




== Problemas conhecidos

Problemas conhecidos identificam problemas que podem impedi-lo de usar o produto com sucesso.

* Ao atualizar um cluster Kubernetes da versão 1.24 para a 1.25 ou posterior que tenha Trident instalado, você deve atualizar o arquivo values.yaml para definir  `excludePodSecurityPolicy` para  `true` ou adicionar  `--set excludePodSecurityPolicy=true` ao comando  `helm upgrade` antes de poder atualizar o cluster.
* Trident agora impõe um valor em branco `fsType` (`fsType=""` para volumes que não possuem o `fsType` especificado em seu StorageClass. Ao trabalhar com Kubernetes 1.17 ou posterior, Trident oferece suporte ao fornecimento de um valor em branco `fsType` para volumes NFS. Para volumes iSCSI, é necessário definir o `fsType` em seu StorageClass ao impor um `fsGroup` usando um contexto de segurança.
* Ao usar um backend em várias instâncias do Trident, cada arquivo de configuração de backend deve ter um valor  `storagePrefix` diferente para backends ONTAP ou usar um valor  `TenantName` diferente para backends SolidFire. O Trident não consegue detectar volumes que outras instâncias do Trident criaram. Tentar criar um volume existente em backends ONTAP ou SolidFire é bem-sucedido, porque o Trident trata a criação de volume como uma operação idempotente. Se  `storagePrefix` ou  `TenantName` não forem diferentes, pode haver colisão de nomes para volumes criados no mesmo backend.
* Ao instalar Trident (usando  `tridentctl` ou o Trident Operator) e usando  `tridentctl` para gerenciar o Trident, você deve garantir que a variável de ambiente  `KUBECONFIG` esteja configurada. Isso é necessário para indicar o cluster Kubernetes que  `tridentctl` deve ser utilizado. Ao trabalhar com múltiplos ambientes Kubernetes, você deve garantir que o arquivo  `KUBECONFIG` seja referenciado corretamente.
* Para realizar exigência de espaço online para iSCSI PVs, o sistema operacional subjacente no nó de trabalho pode exigir que opções de montagem sejam passadas para o volume. Isso é verdade para instâncias RHEL/Red Hat Enterprise Linux CoreOS (RHCOS), que exigem o `discard` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["opção de montagem"^]; certifique-se de que o descarte mountOption esteja incluído em seu[`StorageClass`^] para suportar o descarte de blocos online.
* Se você tiver mais de uma instância do Trident por cluster Kubernetes, Trident não poderá se comunicar com outras instâncias nem descobrir outros volumes que elas criaram, o que leva a comportamentos inesperados e incorretos se mais de uma instância estiver em execução em um cluster. Deve haver apenas uma instância do Trident por cluster Kubernetes.
* Se objetos baseados em Trident  `StorageClass` forem excluídos do Kubernetes enquanto Trident estiver offline, Trident não remove as classes de armazenamento correspondentes do seu banco de dados quando voltar a ficar online. Você deve excluir essas classes de armazenamento usando  `tridentctl` ou a API REST.
* Se um usuário excluir um PV provisionado pelo Trident antes de excluir o PVC correspondente, Trident não exclui automaticamente o volume subjacente. Você deve remover o volume via  `tridentctl` ou a API REST.
* ONTAP não pode provisionar mais de um FlexGroup por vez simultaneamente, a menos que o conjunto de agregados seja exclusivo para cada solicitação de provisionamento.
* Ao usar Trident sobre IPv6, você deve especificar  `managementLIF` e  `dataLIF` na definição do backend entre colchetes. Por exemplo, ``[fd20:8b1e:b258:2000:f816:3eff:feec:0]``.
+

NOTE: Não é possível especificar  `dataLIF` em um backend SAN ONTAP. Trident descobre todas as LIFs iSCSI disponíveis e as utiliza para estabelecer a sessão multipath.

* Se estiver usando o driver  `solidfire-san` com OpenShift 4.5, certifique-se de que os nós de trabalho subjacentes usem MD5 como algoritmo de autenticação CHAP. Algoritmos CHAP seguros compatíveis com FIPS, SHA1, SHA-256 e SHA3-256 estão disponíveis com o Element 12.7.




== Encontre mais informações

* https://github.com/NetApp/trident["Trident GitHub"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Blogs do Trident"^]

