---
sidebar: sidebar 
permalink: trident-managing-k8s/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Saiba mais sobre tridentctl, um utilitĂĄrio de linha de comando que fornece acesso simples ao Trident. 
---
= Gerencie Trident usando tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O https://github.com/NetApp/trident/releases["Pacote de instalaĂ§ĂŁo Trident"^] inclui o `tridentctl` utilitĂĄrio de linha de comando para fornecer acesso simples ao Trident. UsuĂĄrios do Kubernetes com privilĂ©gios suficientes podem usĂĄ-lo para instalar Trident ou gerenciar o namespace que contĂ©m o pod do Trident.



== Comandos e flags globais

VocĂȘ pode executar  `tridentctl help` para obter uma lista de comandos disponĂ­veis para  `tridentctl` ou adicionar a flag  `--help` a qualquer comando para obter uma lista de opĂ§Ă”es e flags para esse comando especĂ­fico.

`tridentctl [command] [--optional-flag]`

O utilitĂĄrio Trident `tridentctl` suporta os seguintes comandos e flags globais.

.Comandos
[%collapsible]
====
`create`:: Adicionar um recurso ao Trident.
`delete`:: Remover um ou mais recursos do Trident.
`get`:: Obtenha um ou mais recursos do Trident.
`help`:: Ajuda sobre qualquer comando.
`images`:: Imprima uma tabela das imagens de contĂȘiner que o Trident precisa.
`import`:: Importe um recurso existente para Trident.
`install`:: Instale Trident.
`logs`:: Imprima os logs do Trident.
`send`:: Envie um recurso do Trident.
`uninstall`:: Desinstale o Trident.
`update`:: Modificar um recurso no Trident.
`update backend state`:: Suspender temporariamente as operaĂ§Ă”es de backend.
`upgrade`:: Atualize um recurso no Trident.
`version`:: Imprima a versĂŁo do Trident.


====
.Bandeiras globais
[%collapsible]
====
`-d`, `--debug`:: SaĂ­da de depuraĂ§ĂŁo.
`-h`, `--help`:: Ajuda para `tridentctl`.
`-k`, `--kubeconfig string`:: Especifique o  `KUBECONFIG` caminho para executar comandos localmente ou de um cluster Kubernetes para outro.
+
--

NOTE: Alternativamente, vocĂȘ pode exportar a  `KUBECONFIG` variĂĄvel para apontar para um cluster Kubernetes especĂ­fico e emitir  `tridentctl` comandos para esse cluster.

--
`-n`, `--namespace string`:: Namespace da implantaĂ§ĂŁo do Trident.
`-o`, `--output string`:: Formato de saĂ­da. Um dos seguintes: json|yaml|name|wide|ps (padrĂŁo).
`-s`, `--server string`:: EndereĂ§o/porta da interface API REST do Trident.
+
--

WARNING: A interface REST do Trident pode ser configurada para escutar e servir apenas em 127.0.0.1 (para IPv4) ou [::1] (para IPv6).

--


====


== OpĂ§Ă”es e parĂąmetros de comando



=== criar

Use o `create` comando para adicionar um recurso ao Trident.

`tridentctl create [option]`

OpĂ§Ă”es:: `backend`: Adicione um backend ao Trident.




=== excluir

Use o comando  `delete` para remover um ou mais recursos do Trident.

`tridentctl delete [option]`

OpĂ§Ă”es:: `backend`: excluir um ou mais backends de armazenamento do Trident.
`snapshot`: excluir um ou mais snapshots de volume do Trident.
`storageclass`: excluir uma ou mais classes de armazenamento do Trident.
`volume`: excluir um ou mais volumes de armazenamento do Trident.




=== get

Use o comando  `get` para obter um ou mais recursos do Trident.

`tridentctl get [option]`

OpĂ§Ă”es:: `backend`: obtenha um ou mais backends de armazenamento do Trident.
`snapshot`: obtenha um ou mais snapshots do Trident.
`storageclass`: obtenha uma ou mais storage classes do Trident.
`volume`: obtenha um ou mais volumes do Trident.
Bandeiras:: `-h`, `--help`: ajuda para volumes.
`--parentOfSubordinate string`: limitar a consulta ao volume de origem subordinado.
`--subordinateOf string`: limitar a consulta aos subordinados do volume.




=== imagens

Use  `images` flags para imprimir uma tabela com as imagens dos contĂȘineres que o Trident precisa.

`tridentctl images [flags]`

Bandeiras:: `-h`, `--help`: ajuda para imagens.
`-v`, `--k8s-version string`: versĂŁo semĂąntica do cluster Kubernetes.




=== importar volume

Use o  `import volume` comando para importar um volume existente para Trident.

`tridentctl import volume <backendName> <volumeName> [flags]`

Aliases:: `volume`, `v`
Bandeiras:: `-f`, `--filename string`: Caminho para o arquivo PVC em YAML ou JSON.
`-h`, `--help`: Ajuda para volume.
`--no-manage`: Criar somente PV/PVC. NĂŁo assumir gerenciamento de ciclo de vida do volume.




=== instalar

Use os  `install` flags para instalar Trident.

`tridentctl install [flags]`

Bandeiras:: `--autosupport-image string`: A imagem do contĂȘiner para Autosupport Telemetry (padrĂŁo "netapp/trident autosupport:<current-version>").
`--autosupport-proxy string`: O endereĂ§o/porta de um proxy para envio de Autosupport Telemetry.
`--enable-node-prep`: Tentar instalar os pacotes necessĂĄrios nos nĂłs.
`--generate-custom-yaml`: Gerar arquivos YAML sem instalar nada.
`-h`, `--help`: Ajuda para instalaĂ§ĂŁo.
`--http-request-timeout`: Substituir o tempo limite de solicitaĂ§ĂŁo HTTP para a API REST do Trident (padrĂŁo 1m30s).
`--image-registry string`: O endereĂ§o/porta de um registro de imagens interno.
`--k8s-timeout duration`: O tempo limite para todas as operaĂ§Ă”es do Kubernetes (padrĂŁo 3m0s).
`--kubelet-dir string`: O local do host do estado interno do kubelet (padrĂŁo "/var/lib/kubelet").
`--log-format string`: O formato de log do Trident (text, json) (padrĂŁo "text").
`--node-prep`: Permite que o Trident prepare os nĂłs do cluster Kubernetes para gerenciar volumes usando o protocolo de storage de dados especificado. *Atualmente,  `iscsi` Ă© o Ășnico valor suportado. A partir do OpenShift 4.19, a versĂŁo mĂ­nima do Trident compatĂ­vel com este recurso Ă© 25.06.1.*
`--pv string`: O nome do PV legado usado pelo Trident; certifique-se de que ele nĂŁo exista (padrĂŁo "trident").
`--pvc string`: O nome do PVC legado usado pelo Trident; certifique-se de que ele nĂŁo exista (padrĂŁo "trident").
`--silence-autosupport`: NĂŁo enviar pacotes autosupport para NetApp automaticamente (padrĂŁo true).
`--silent`: Desativar a maior parte da saĂ­da durante a instalaĂ§ĂŁo.
`--trident-image string`: A imagem do Trident a ser instalada.
`--k8s-api-qps`: O limite de consultas por segundo (QPS) para solicitaĂ§Ă”es da API do Kubernetes (padrĂŁo 100; opcional).
`--use-custom-yaml`: Usar quaisquer arquivos YAML existentes no diretĂłrio de setup.
`--use-ipv6`: Usar IPv6 para a comunicaĂ§ĂŁo do Trident.




=== registros

Use  `logs`flags para imprimir os logs do Trident.

`tridentctl logs [flags]`

Bandeiras:: `-a`, `--archive`: Crie um arquivo de suporte com todos os logs, a menos que especificado de outra forma.
`-h`, `--help`: Ajuda para logs.
`-l`, `--log string`: Log do Trident a ser exibido. Um de trident|auto|trident-operator|all (padrĂŁo "auto").
`--node string`: O nome do nĂł do Kubernetes do qual coletar os logs do pod do nĂł.
`-p`, `--previous`: Obtenha os logs da instĂąncia anterior do contĂȘiner, se existir.
`--sidecars`: Obtenha os logs dos contĂȘineres sidecar.




=== enviar

Use o comando  `send` para enviar um recurso do Trident.

`tridentctl send [option]`

OpĂ§Ă”es:: `autosupport`: Envie um arquivo de Autosupport para NetApp.




=== desinstalar

Use  `uninstall`parĂąmetros para desinstalar Trident.

`tridentctl uninstall [flags]`

Bandeiras:: `-h, --help`: Ajuda para desinstalar.
`--silent`: Desativar a maior parte da saĂ­da durante a desinstalaĂ§ĂŁo.




=== atualizar

Use o  `update` comando para modificar um recurso no Trident.

`tridentctl update [option]`

OpĂ§Ă”es:: `backend`: Atualizar um backend no Trident.




=== atualizar estado do backend

Use o comando  `update backend state` para suspender ou retomar as operaĂ§Ă”es de backend.

`tridentctl update backend state <backend-name> [flag]`

.Pontos a considerar
* Se um backend for criado usando um TridentBackendConfig (tbc), o backend nĂŁo poderĂĄ ser atualizado usando um arquivo  `backend.json`.
* Se o  `userState` tiver sido definido em um tbc, ele nĂŁo poderĂĄ ser modificado usando o comando  `tridentctl update backend state <backend-name> --user-state suspended/normal`.
* Para recuperar a capacidade de definir o `userState` via tridentctl apĂłs ter sido definido via tbc, o campo `userState` deve ser removido do tbc. Isso pode ser feito usando o comando `kubectl edit tbc`. ApĂłs o campo `userState` ser removido, vocĂȘ pode usar o comando `tridentctl update backend state` para alterar o `userState` de um backend.
* Use o  `tridentctl update backend state` para alterar o  `userState`. VocĂȘ tambĂ©m pode atualizar o  `userState` usando  `TridentBackendConfig` ou  `backend.json` arquivo; isso aciona uma reinicializaĂ§ĂŁo completa do backend e pode ser demorado.
+
Bandeiras:: `-h`, `--help`: Ajuda para o estado do backend.
`--user-state`: Defina como `suspended` para pausar as operaĂ§Ă”es do backend. Defina como `normal` para retomar as operaĂ§Ă”es do backend. Quando definido como `suspended`:


* `AddVolume` e  `Import Volume` estĂŁo em pausa.
* `CloneVolume`, `ResizeVolume`, `PublishVolume`, `UnPublishVolume`, `CreateSnapshot`, `GetSnapshot`, `RestoreSnapshot`, `DeleteSnapshot`, `RemoveVolume`, `GetVolumeExternal`, `ReconcileNodeAccess` permanecem disponĂ­veis.


VocĂȘ tambĂ©m pode atualizar o estado do backend usando  `userState` campo no arquivo de configuraĂ§ĂŁo do backend `TridentBackendConfig` ou `backend.json`. Para mais informaĂ§Ă”es, consulte link:../trident-use/backend_options.html["OpĂ§Ă”es para gerenciamento de backends"] e link:../trident-use/backend_ops_kubectl.html["Realize o gerenciamento de backend com kubectl"].

*Exemplo:*

[role="tabbed-block"]
====
.JSON
--
Siga estes passos para atualizar o `userState` usando o arquivo `backend.json`:

. Edite o  `backend.json` arquivo para incluir o  `userState` campo com o valor definido como 'suspended'.
. Atualize o backend usando o  `tridentctl update backend` comando e o caminho para o arquivo  `backend.json` atualizado.
+
*Exemplo*: `tridentctl update backend  -f /<path to backend JSON file>/backend.json -n trident`



[listing]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "<redacted>",
  "svm": "nas-svm",
  "backendName": "customBackend",
  "username": "<redacted>",
  "password": "<redacted>",
  "userState": "suspended"
}

----
--
.YAML
--
VocĂȘ pode editar o tbc depois que ele for aplicado usando o  `kubectl edit <tbc-name> -n <namespace>` comando. O exemplo a seguir atualiza o estado do backend para suspender usando a  `userState: suspended` opĂ§ĂŁo:

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-ontap-nas
spec:
  version: 1
  backendName: customBackend
  storageDriverName: ontap-nas
  managementLIF: <redacted>
  svm: nas-svm
  userState: suspended
  credentials:
    name: backend-tbc-ontap-nas-secret
----
--
====


=== versĂŁo

Use  `version` flags para imprimir a versĂŁo de  `tridentctl` e o serviĂ§o Trident em execuĂ§ĂŁo.

`tridentctl version [flags]`

Bandeiras:: `--client`: somente versĂŁo cliente (nĂŁo requer servidor).
`-h, --help`: ajuda para versĂŁo.




== Suporte a plugin

O Tridentctl suporta plugins de forma semelhante ao kubectl. O Tridentctl detecta um plugin se o nome do arquivo binĂĄrio do plugin seguir o esquema "tridentctl-<plugin>" e o binĂĄrio estiver localizado em uma pasta listada na variĂĄvel de ambiente PATH. Todos os plugins detectados sĂŁo listados na seĂ§ĂŁo de plugins da ajuda do tridentctl. Opcionalmente, vocĂȘ tambĂ©m pode limitar a busca especificando uma pasta de plugin na variĂĄvel de ambiente TRIDENTCTL_PLUGIN_PATH (Exemplo: `TRIDENTCTL_PLUGIN_PATH=~/tridentctl-plugins/`). Se a variĂĄvel for usada, o tridentctl buscarĂĄ apenas na pasta especificada.
