---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Saiba mais sobre como configurar um backend ONTAP com drivers ONTAP SAN. 
---
= Visão geral do driver ONTAP SAN
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre como configurar um backend ONTAP com os drivers SAN do ONTAP e do Cloud Volumes ONTAP.



== Detalhes do driver ONTAP SAN

Trident fornece os seguintes drivers de armazenamento SAN para se comunicar com o ONTAP cluster. Os modos de acesso suportados são: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Driver | Protocolo | volumeMode | Modos de acesso suportados | Sistemas de arquivos suportados 


| `ontap-san`  a| 
iSCSI SCSI sobre FC
 a| 
Bloco
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san`  a| 
iSCSI SCSI sobre FC
 a| 
Sistema de arquivos
 a| 
RWO, RWOP

ROX e RWX não estão disponíveis no modo de volume de sistema de arquivos.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san`  a| 
NVMe/TCP

Consulte <<Considerações adicionais para NVMe/TCP>>.
 a| 
Bloco
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san`  a| 
NVMe/TCP

Consulte <<Considerações adicionais para NVMe/TCP>>.
 a| 
Sistema de arquivos
 a| 
RWO, RWOP

ROX e RWX não estão disponíveis no modo de volume de sistema de arquivos.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san-economy`  a| 
iSCSI
 a| 
Bloco
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san-economy`  a| 
iSCSI
 a| 
Sistema de arquivos
 a| 
RWO, RWOP

ROX e RWX não estão disponíveis no modo de volume de sistema de arquivos.
 a| 
`xfs`, `ext3`, `ext4`

|===
[WARNING]
====
* Use  `ontap-san-economy` somente se a contagem de uso de volume persistente prevista for maior que link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limites de volume ONTAP suportados"^].
* Use  `ontap-nas-economy` somente se a contagem de uso de volume persistente prevista for maior que link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limites de volume ONTAP suportados"^] e o driver  `ontap-san-economy` não puder ser usado.
* Não utilize  `ontap-nas-economy` se você prevê a necessidade de proteção de dados, recuperação de desastres ou mobilidade.
* NetApp não recomenda usar o crescimento automático do FlexVol em todos os drivers ONTAP, exceto ontap-san. Como alternativa, Trident oferece suporte ao uso de reserva de snapshot e dimensiona os volumes FlexVol de acordo.


====


== Permissões do usuário

Trident espera ser executado como administrador do ONTAP ou do SVM, normalmente usando o `admin` usuário do cluster ou um `vsadmin` usuário do SVM, ou um usuário com um nome diferente que tenha a mesma função. Para implantações do Amazon FSx for NetApp ONTAP, Trident espera ser executado como administrador do ONTAP ou do SVM, usando o usuário do cluster `fsxadmin` ou um usuário do SVM `vsadmin`, ou um usuário com um nome diferente que tenha a mesma função. O `fsxadmin` usuário é um substituto limitado para o usuário administrador do cluster.


NOTE: Se você usar o `limitAggregateUsage`parâmetro, são necessárias permissões de administrador do cluster. Ao usar Amazon FSx for NetApp ONTAP com Trident, o `limitAggregateUsage`parâmetro não funcionará com as contas de usuário `vsadmin`e `fsxadmin`. A operação de configuração falhará se você especificar este parâmetro.

Embora seja possível criar uma função mais restritiva dentro do ONTAP que um driver Trident possa usar, não recomendamos isso. A maioria das novas versões do Trident chamará APIs adicionais que precisariam ser consideradas, dificultando as atualizações e tornando-as propensas a erros.



== Considerações adicionais para NVMe/TCP

Trident suporta o protocolo non-volatile memory express (NVMe) usando o  `ontap-san` driver incluindo:

* IPv6
* Instantâneos e clones de volumes NVMe
* Redimensionando um volume NVMe
* Importando um volume NVMe criado fora do Trident para que seu ciclo de vida possa ser gerenciado pelo Trident
* Multipathing nativo NVMe
* Encerramento correto ou incorreto dos nós K8s (24.06)


Trident não suporta:

* DH-HMAC-CHAP que é suportado nativamente pelo NVMe
* Multipathing do device mapper (DM)
* LUKS criptografia



NOTE: O NVMe é suportado apenas com as APIs REST do ONTAP e não é suportado com ONTAPI (ZAPI).
