---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: 'Ao usar Trident com Amazon FSx for NetApp ONTAP, você pode garantir que seus clusters Kubernetes em execução no Amazon Elastic Kubernetes Service (EKS) possam provisionar volumes persistentes em bloco e em arquivo com suporte do ONTAP.' 
---
= Use Trident com Amazon FSx for NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP"^] é um serviço totalmente gerenciado da AWS que permite aos clientes lançar e executar sistemas de arquivos baseados no sistema operacional de storage NetApp ONTAP. FSx for ONTAP permite que você aproveite os recursos, o desempenho e as capacidades administrativas do NetApp com os quais você já está familiarizado, enquanto aproveita a simplicidade, agilidade, segurança e escalabilidade de armazenar dados na AWS. FSx for ONTAP oferece suporte aos recursos do sistema de arquivos ONTAP e às APIs de administração.

Você pode integrar seu Amazon FSx for NetApp ONTAP file system com Trident para garantir que clusters Kubernetes em execução no Amazon Elastic Kubernetes Service (EKS) possam provisionar volumes persistentes de bloco e de arquivo com suporte do ONTAP.

Um sistema de arquivos é o recurso principal no Amazon FSx, análogo a um cluster ONTAP em infraestrutura local. Dentro de cada SVM você pode criar um ou mais volumes, que são contêineres de dados que armazenam os arquivos e pastas no seu sistema de arquivos. Com Amazon FSx for NetApp ONTAP será fornecido como um sistema de arquivos gerenciado na nuvem. O novo tipo de sistema de arquivos é chamado *NetApp ONTAP*.

Ao usar Trident com Amazon FSx para NetApp ONTAP, você pode garantir que clusters Kubernetes em execução no Amazon Elastic Kubernetes Service (EKS) possam provisionar volumes persistentes em bloco e em arquivo com suporte do ONTAP.



== Requisitos

Além de link:../trident-get-started/requirements.html["Requisitos do Trident"], para integrar o FSx for ONTAP com Trident, você precisa de:

* Um cluster Amazon EKS existente ou um cluster Kubernetes autogerenciado com  `kubectl` instalado.
* Um sistema de arquivos Amazon FSx for NetApp ONTAP e uma máquina virtual de armazenamento (SVM) existentes que sejam acessíveis a partir dos nós de trabalho do seu cluster.
* Nós de trabalho preparados para link:worker-node-prep.html["NFS ou iSCSI"].
+

NOTE: Certifique-se de seguir os passos de preparação do nó necessários para Amazon Linux e Ubuntu https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Amazon Machine Images"^] (AMIs), dependendo do seu tipo de AMI do EKS.





== Considerações

* Volumes SMB:
+
** Os volumes SMB são suportados usando apenas o driver `ontap-nas`.
** Os volumes SMB não são suportados com o Trident EKS add-on.
** Trident suporta volumes SMB montados em pods executados apenas em nós Windows. Consulte link:../trident-use/trident-fsx-storage-backend.html#prepare-to-provision-smb-volumes["Prepare-se para provisionar volumes SMB"] para obter detalhes.


* Antes do Trident 24.02, volumes criados em sistemas de arquivos Amazon FSx que tinham backups automáticos ativados não podiam ser excluídos pelo Trident. Para evitar esse problema no Trident 24.02 ou posterior, especifique o `fsxFilesystemID`, AWS `apiRegion`, AWS `apikey` e AWS `secretKey` no arquivo de configuração do backend para AWS FSx for ONTAP.
+

NOTE: Se você estiver especificando uma função do IAM para Trident, poderá omitir a especificação dos campos  `apiRegion`, `apiKey` e  `secretKey` para o Trident explicitamente. Para mais informações, consulte link:../trident-use/trident-fsx-examples.html["Opções e exemplos de configuração do FSx for ONTAP"].





=== Uso simultâneo do Trident SAN/iSCSI e do driver EBS-CSI

Se você planeja usar drivers ontap-san (por exemplo, iSCSI) com AWS (EKS, ROSA, EC2 ou qualquer outra instância), a configuração de multipath necessária nos nós pode entrar em conflito com o driver CSI do Amazon Elastic Block Store (EBS). Para garantir que o multipath funcione sem interferir nos discos EBS no mesmo nó, você precisa excluir EBS da sua configuração de multipath. Este exemplo mostra um  `multipath.conf`arquivo que inclui as configurações necessárias do Trident, excluindo os discos EBS do multipath:

[listing]
----
defaults {
    find_multipaths no
}
blacklist {
    device {
        vendor "NVME"
        product "Amazon Elastic Block Store"
    }
}
----


== Autenticação

Trident oferece dois modos de autenticação.

* Baseado em credenciais (recomendado): armazena as credenciais com segurança no AWS Secrets Manager. Você pode usar o  `fsxadmin` usuário do seu sistema de arquivos ou o  `vsadmin` usuário configurado para sua SVM.
+

WARNING: Trident espera ser executado como um `vsadmin` usuário SVM ou como um usuário com um nome diferente que tenha a mesma função. Amazon FSx for NetApp ONTAP possui um `fsxadmin` usuário que é um substituto limitado para o ONTAP `admin` cluster user. Recomendamos fortemente usar `vsadmin` com Trident.

* Com base em certificado: Trident se comunicará com a SVM no seu sistema de arquivos FSx usando um certificado instalado na sua SVM.


Para obter detalhes sobre como ativar a autenticação, consulte a autenticação para o seu tipo de driver:

* link:ontap-nas-prep.html["ONTAP NAS autenticação"]
* link:ontap-san-prep.html["ONTAP SAN autenticação"]




== Imagens de Máquina da Amazon (AMIs) testadas

O cluster EKS suporta diversos sistemas operacionais, mas a AWS otimizou determinadas Amazon Machine Images (AMIs) para contêineres e EKS. As seguintes AMIs foram testadas com NetApp Trident 25.02.

|===


| AMI | NAS | NAS-economy | iSCSI | iSCSI-economia 


| AL2023_x86_64_STANDARD | Sim | Sim | Sim | Sim 


| AL2_x86_64 | Sim | Sim | Sim* | Sim* 


| BOTTLEROCKET_x86_64 | Sim** | Sim | N/A | N/A 


| AL2023_ARM_64_STANDARD | Sim | Sim | Sim | Sim 


| AL2_ARM_64 | Sim | Sim | Sim* | Sim* 


| BOTTLEROCKET_ARM_64 | Sim** | Sim | N/A | N/A 
|===
* * Não foi possível excluir o PV sem reiniciar o nó
* ** Não funciona com NFSv3 com Trident versão 25.02.



NOTE: Se a AMI desejada não estiver listada aqui, isso não significa que ela não seja compatível; significa apenas que ela não foi testada. Esta lista serve como um guia para AMIs que comprovadamente funcionam.

*Testes realizados com*:

* Versão do EKS: 1.32
* Método de instalação: Helm 25.06 e como um AWS add-On 25.06
* Para NAS, foram testados tanto NFSv3 quanto NFSv4.1.
* Para SAN, apenas iSCSI foi testado, não NVMe-oF.


*Testes realizados*:

* Criar: classe de armazenamento, pvc, pod
* Excluir: pod, pvc (regular, qtree/lun – econômico, NAS com backup da AWS)




== Encontre mais informações

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Documentação do Amazon FSx for NetApp ONTAP"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["Postagem no blog sobre Amazon FSx for NetApp ONTAP"^]

