---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: 'Ao usar Trident com Amazon FSx for NetApp ONTAP, você pode garantir que seus clusters Kubernetes em execução no Amazon Elastic Kubernetes Service (EKS) possam provisionar volumes persistentes em bloco e em arquivo com suporte do ONTAP.' 
---
= Instale Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident simplifica o gerenciamento de storage do Amazon FSx for NetApp ONTAP no Kubernetes para permitir que seus desenvolvedores e administradores se concentrem na implantação de aplicativos.

Você pode instalar Trident usando um dos seguintes métodos:

* Helm
* Complemento do EKS


Se você deseja utilizar a funcionalidade de instantâneo, instale o complemento do controlador de instantâneo CSI. Consulte link:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["Ative a funcionalidade de instantâneo para volumes CSI"^] para mais informações.



== Instale Trident via helm

[role="tabbed-block"]
====
.Identidade do Pod
--
. Adicione o repositório Trident:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Instale Trident usando o seguinte exemplo:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
Você pode usar o  `helm list` comando para revisar detalhes da instalação, como nome, namespace, chart, status, versão do aplicativo e número da revisão.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.Associação de conta de serviço (IRSA)
--
. Adicione o repositório Trident:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Defina os valores para *provedor de nuvem* e *identidade de nuvem*:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
Você pode usar o  `helm list` comando para revisar detalhes da instalação, como nome, namespace, chart, status, versão do aplicativo e número da revisão.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2510.0    25.10.0
----


--
====
[NOTE]
====
Se você pretende usar iSCSI, certifique-se de que o iSCSI esteja habilitado em sua máquina cliente. Se você estiver usando o sistema operacional AL2023 Worker node, é possível automatizar a instalação do cliente iSCSI adicionando o parâmetro node prep na instalação do helm:

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== Instale o Trident via o add-on EKS

O Trident EKS add-on inclui os patches de segurança mais recentes, correções de bugs e é validado pela AWS para funcionar com o Amazon EKS. O EKS add-on permite garantir de forma consistente que seus clusters Amazon EKS estejam seguros e estáveis e reduz a quantidade de trabalho necessária para instalar, configurar e atualizar add-ons.



=== Pré-requisitos

Certifique-se de ter o seguinte antes de configurar o add-on Trident para AWS EKS:

* Uma conta de cluster Amazon EKS com assinatura adicional
* Permissões da AWS para o AWS marketplace:
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* Tipo de AMI: Amazon Linux 2 (AL2_x86_64) ou Amazon Linux 2 Arm(AL2_ARM_64)
* Tipo de nó: AMD ou ARM
* Um sistema de arquivos Amazon FSx for NetApp ONTAP existente




=== Habilite o complemento Trident para AWS

[role="tabbed-block"]
====
.Console de gerenciamento
--
. Abra o console do Amazon EKS em https://console.aws.amazon.com/eks/home#/clusters[].
. No painel de navegação à esquerda, selecione *Clusters*.
. Selecione o nome do cluster para o qual deseja configurar o complemento Trident CSI da NetApp.
. Selecione *Complementos* e depois selecione *Obter mais complementos*.
. Siga estes passos para selecionar o software complementar:
+
.. Desça a página até a seção *Complementos do AWS Marketplace* e digite *"Trident”* na caixa de pesquisa.
.. Selecione a caixa de seleção no canto superior direito da caixa Trident by NetApp.
.. Selecione *Next*.


. Na página de configurações *Configurar add-ons selecionados*, faça o seguinte:
+

NOTE: *Ignore estas etapas se estiver usando a associação de Pod Identity.*

+
.. Selecione a *Version* que deseja usar.
.. Se você estiver usando autenticação IRSA, certifique-se de definir os valores de configuração disponíveis nas configurações opcionais:
+
*** Selecione a *Version* que deseja usar.
*** Siga o *esquema de configuração do complemento* e defina o parâmetro *configurationValues* na seção *Valores de configuração* para o role-arn que você criou na etapa anterior (o valor deve estar no seguinte formato):




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
  "cloudProvider": "AWS"

}
----
+
Se você selecionar Override como método de resolução de conflitos, uma ou mais configurações do add-on existente poderão ser substituídas pelas configurações do add-on do Amazon EKS. Se você não habilitar esta opção e houver um conflito com suas configurações existentes, a operação falhará. Você pode usar a mensagem de erro resultante para solucionar o conflito. Antes de selecionar esta opção, certifique-se de que o add-on do Amazon EKS não gerencie configurações que você precise gerenciar manualmente.

. Escolha *Próximo*.
. Na página *Revisar e adicionar*, escolha *Criar*.
+
Após a conclusão da instalação do complemento, você verá o complemento instalado.



--
.AWS CLI
--
*1. Crie o  `add-on.json` arquivo*:

*Para Pod Identity, utilize o seguinte formato*:


NOTE: Use o

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
}
----
*Para autenticação IRSA, utilize o seguinte formato*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: Substitua  `<role ARN>` pelo ARN da função que foi criada na etapa anterior.

*2. Instale o complemento Trident EKS.*

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksctl
--
O seguinte comando de exemplo instala o Trident EKS add-on:

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== Atualize o complemento Trident EKS

[role="tabbed-block"]
====
.Console de gerenciamento
--
. Abra o console do Amazon EKS https://console.aws.amazon.com/eks/home#/clusters[].
. No painel de navegação à esquerda, selecione *Clusters*.
. Selecione o nome do cluster para o qual deseja atualizar o software complementar NetApp Trident CSI.
. Selecione a guia *Add-ons*.
. Selecione *Trident por NetApp* e depois selecione *Editar*.
. Na página *Configurar Trident por NetApp*, faça o seguinte:
+
.. Selecione a *Version* que deseja usar.
.. Expanda as *Configurações opcionais de configuração* e modifique conforme necessário.
.. Selecione *Save changes*.




--
.AWS CLI
--
O exemplo a seguir atualiza o add-on EKS:

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.6.0-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksctl
--
* Verifique a versão atual do seu FSxN Trident CSI add-on. Substitua  `my-cluster` pelo nome do seu cluster.
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*Exemplo de saída:*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.6.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* Atualize o software complementar para a versão retornada em UPDATE AVAILABLE na saída da etapa anterior.
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.6.0-eksbuild.1 --cluster my-cluster --force
----


Se você remover a  `--force` opção e alguma das configurações do add-on do Amazon EKS entrar em conflito com suas configurações existentes, a atualização do add-on do Amazon EKS falhará; você receberá uma mensagem de erro para ajudá-lo a resolver o conflito. Antes de especificar esta opção, certifique-se de que o add-on do Amazon EKS não gerencie configurações que você precisa gerenciar, pois essas configurações serão sobrescritas com esta opção. Para mais informações sobre outras opções para esta configuração, consulte link:https://eksctl.io/usage/addons/["Complementos"]. Para mais informações sobre o gerenciamento de campos do Kubernetes no Amazon EKS, consulte link:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["Gerenciamento de campos do Kubernetes"].

--
====


=== Desinstalar/remover o Trident EKS add-on

Você tem duas opções para remover um add-on do Amazon EKS:

* *Preservar software complementar no seu cluster* – Esta opção remove o gerenciamento de quaisquer configurações pelo Amazon EKS. Ela também remove a capacidade do Amazon EKS de notificá-lo sobre atualizações e atualizar automaticamente o add-on do Amazon EKS após você iniciar uma atualização. No entanto, ela preserva o software complementar no seu cluster. Esta opção transforma o add-on em uma instalação autogerenciada, em vez de um add-on do Amazon EKS. Com esta opção, não há tempo de inatividade para o add-on. Mantenha a `--preserve` opção no comando para preservar o add-on.
* *Remova o software complementar completamente do seu cluster* – NetApp recomenda que você remova o complemento do Amazon EKS do seu cluster somente se não houver recursos no seu cluster que dependam dele. Remova a  `--preserve` opção do comando  `delete` para remover o software complementar.



NOTE: Se o software complementar tiver uma conta IAM associada a ele, a conta IAM não será removida.

[role="tabbed-block"]
====
.Console de gerenciamento
--
. Abra o console do Amazon EKS em https://console.aws.amazon.com/eks/home#/clusters[].
. No painel de navegação à esquerda, selecione *Clusters*.
. Selecione o nome do cluster do qual você deseja remover o complemento NetApp Trident CSI.
. Selecione a aba *Complementos* e depois selecione *Trident by NetApp*.*
. Selecione *Remove*.
. Na caixa de diálogo *Remover netapp_trident-operator confirmation*, faça o seguinte:
+
.. Se você deseja que o Amazon EKS pare de gerenciar as configurações do software complementar, selecione *Preservar no cluster*. Faça isso se quiser manter o software complementar no seu cluster para que você possa gerenciar todas as configurações do software complementar por conta própria.
.. Digite *netapp_trident-operator*.
.. Selecione *Remove*.




--
.AWS CLI
--
Substitua  `my-cluster` pelo nome do seu cluster e, em seguida, execute o seguinte comando.

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksctl
--
O comando a seguir desinstala o Trident EKS add-on:

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====