---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-operator-mirror.html 
keywords: deploy, Trident, methods, operator, tridentctl, mirrored, registry, registries 
summary: Você pode implantar manualmente o operador Trident para instalar o Trident. Esse processo se aplica a instalações em que as imagens de contêiner necessárias para o Trident estão armazenadas em um registro privado. 
---
= Implantar manualmente o operador Trident (modo offline)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode implantar manualmente o operador Trident para instalar Trident. Esse processo se aplica a instalações em que as imagens de contêiner necessárias para Trident estão armazenadas em um registro privado. Se você não tiver um registro de imagens privado, use o link:kubernetes-deploy-operator.html["processo para implantação padrão"].



== Informações críticas sobre Trident10

*Você deve ler as seguintes informações críticas sobre Trident.*

.<strong>Informações críticas sobre Trident</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 agora é compatível com Trident. Atualize Trident antes de atualizar Kubernetes.
* Trident impõe rigorosamente o uso da configuração de multipath em ambientes SAN, com um valor recomendado de  `find_multipaths: no` no arquivo multipath.conf.
+
O uso de configuração sem multipath ou o uso de  `find_multipaths: yes` ou  `find_multipaths: smart` valor no arquivo multipath.conf resultará em falhas de montagem. Trident recomenda o uso de  `find_multipaths: no` desde o lançamento 21.07.



=====
====


== Implante manualmente o operador Trident e instale o Trident

Revise link:../trident-get-started/kubernetes-deploy.html["visão geral da instalação"] para garantir que você atendeu aos pré-requisitos de instalação e selecionou a opção de instalação correta para o seu ambiente.

.Antes de começar
Faça login no host Linux e verifique se ele está gerenciando um sistema operacional em funcionamento link:requirements.html["cluster Kubernetes suportado"^] e se você possui os privilégios necessários.


NOTE: Com OpenShift, use  `oc` em vez de  `kubectl` em todos os exemplos a seguir e faça login como *system:admin* primeiro executando  `oc login -u system:admin` ou  `oc login -u kube-admin`.

[%collapsible%open]
====
. Verifique sua versão do Kubernetes:
+
[listing]
----
kubectl version
----
. Verifique privilégios de administrador do cluster:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Verifique se você consegue iniciar um pod que utiliza uma imagem do Docker Hub e acessar seu sistema de storage pela rede de pods:
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


=== Passo 1: Baixe o pacote de instalação do Trident

O pacote de instalação do Trident contém tudo o que você precisa para implantar o operador Trident e instalar o Trident. Baixe e extraia a versão mais recente do instalador do Trident em link:https://github.com/NetApp/trident/releases/latest["a seção _Ativos_ em GitHub"^].

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v6.0/trident-installer-25.10.0.tar.gz
tar -xf trident-installer-25.10.0.tar.gz
cd trident-installer
----


=== Etapa 2: criar o  `TridentOrchestrator`CRD

Crie a `TridentOrchestrator` Definição de Recurso Personalizado (CRD). Você criará um `TridentOrchestrator` Recurso Personalizado posteriormente. Use a versão YAML apropriada da CRD em `deploy/crds` para criar a `TridentOrchestrator` CRD:

[listing]
----
kubectl create -f deploy/crds/<VERSION>.yaml
----


=== Etapa 3: atualize o local do registro no operador

Em  `/deploy/operator.yaml`, atualize  `image: docker.io/netapp/trident-operator:25.10.0` para refletir a localização do seu registro de imagens. Seu link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Imagens do Trident e do CSI"] pode estar localizado em um único registro ou em registros diferentes, mas todas as imagens CSI devem estar localizadas no mesmo registro. Por exemplo:

* `image: <your-registry>/trident-operator:25.10.0` se todas as suas imagens estiverem localizadas em um único registro.
* `image: <your-registry>/netapp/trident-operator:25.10.0` se a sua imagem Trident estiver localizada em um registro diferente das suas imagens CSI.




=== Etapa 4: implante o operador Trident

O instalador do Trident fornece um arquivo de pacote que pode ser usado para instalar o operador e criar objetos associados. O arquivo de pacote é uma maneira fácil de implantar o operador e instalar Trident usando uma configuração padrão.

* Para clusters executando Kubernetes 1.24, use `bundle_pre_1_25.yaml`.
* Para clusters executando Kubernetes 1.25 ou posterior, use `bundle_post_1_25.yaml`.


.Antes de começar
* Por padrão, o instalador do Trident implanta o operador no  `trident` namespace. Se o  `trident` namespace não existir, crie-o usando:
+
[listing]
----
kubectl apply -f deploy/namespace.yaml
----
* Para implantar o operador em um namespace diferente do `trident` namespace, atualize `serviceaccount.yaml`, `clusterrolebinding.yaml` e `operator.yaml` e gere seu arquivo de pacote usando o `kustomization.yaml`.
+
.. Crie o  `kustomization.yaml` usando o seguinte comando onde _<bundle.yaml>_ é  `bundle_pre_1_25.yaml` ou  `bundle_post_1_25.yaml` com base na sua versão do Kubernetes.
+
[listing]
----
cp deploy/kustomization_<bundle.yaml> deploy/kustomization.yaml
----
.. Compile o pacote usando o seguinte comando, onde _<bundle.yaml>_ é  `bundle_pre_1_25.yaml` ou  `bundle_post_1_25.yaml` com base na sua versão do Kubernetes.
+
[listing]
----
kubectl kustomize deploy/ > deploy/<bundle.yaml>
----




.Passos
. Crie os recursos e implemente o operador:
+
[listing]
----
kubectl create -f deploy/<bundle.yaml>
----
. Verifique se o operador, a implantação e os replicasets foram criados.
+
[listing]
----
kubectl get all -n <operator-namespace>
----



IMPORTANT: Deve haver apenas *uma instância* do operador em um cluster Kubernetes. Não crie várias implantações do operador Trident.



=== Etapa 5: atualize o local do registro de imagens no `TridentOrchestrator`

Seu link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Imagens do Trident e do CSI"] pode estar localizado em um registro ou em registros diferentes, mas todas as imagens CSI devem estar no mesmo registro. Atualize  `deploy/crds/tridentorchestrator_cr.yaml` para adicionar as especificações de localização adicionais com base na sua configuração de registro.

[role="tabbed-block"]
====
.Imagens em um registro
--
[listing]
----
imageRegistry: "<your-registry>"
autosupportImage: "<your-registry>/trident-autosupport:25.10"
tridentImage: "<your-registry>/trident:25.10.0"
----
--
.Imagens em diferentes repositórios
--
[listing]
----
imageRegistry: "<your-registry>"
autosupportImage: "<your-registry>/trident-autosupport:25.10"
tridentImage: "<your-registry>/trident:25.10.0"
----
--
====


=== Etapa 6: Crie o `TridentOrchestrator` e instale Trident

Agora você pode criar o `TridentOrchestrator` e instalar o Trident. Opcionalmente, você pode link:kubernetes-customize-deploy.html["Personalize a sua instalação do Trident"]personalizar usando os atributos na especificação  `TridentOrchestrator`. O exemplo a seguir mostra uma instalação onde as imagens do Trident e do CSI estão localizadas em registros diferentes.

[listing]
----
kubectl create -f deploy/crds/tridentorchestrator_cr.yaml
tridentorchestrator.trident.netapp.io/trident created

kubectl describe torc trident

Name:        trident
Namespace:
Labels:      <none>
Annotations: <none>
API Version: trident.netapp.io/v1
Kind:        TridentOrchestrator
...
Spec:
  Autosupport Image:  <your-registry>/trident-autosupport:25.10
  Debug:              true
  Image Registry:     <your-registry>
  Namespace:          trident
  Trident Image:      <your-registry>/trident:25.10.0
Status:
  Current Installation Params:
    IPv6:                       false
    Autosupport Hostname:
    Autosupport Image:          <your-registry>/trident-autosupport:25.10
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                      true
    Http Request Timeout:       90s
    Image Pull Secrets:
    Image Registry:       <your-registry>
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Probe Port:           17546
    Silence Autosupport:  false
    Trident Image:        <your-registry>/trident:25.10.0
  Message:                Trident installed
  Namespace:              trident
  Status:                 Installed
  Version:                v25.10.0
Events:
    Type Reason Age From Message ---- ------ ---- ---- -------Normal
    Installing 74s trident-operator.netapp.io Installing Trident Normal
    Installed 67s trident-operator.netapp.io Trident installed
----


== Verifique a instalação

Existem várias maneiras de verificar sua instalação.



=== Usando  `TridentOrchestrator` status

O status de `TridentOrchestrator` indica se a instalação foi bem-sucedida e exibe a versão do Trident instalada. Durante a instalação, o status de `TridentOrchestrator` muda de `Installing` para `Installed`. Se você observar o status de `Failed` e o operador não conseguir se recuperar sozinho, link:../troubleshooting.html["verifique os logs"].

[cols="2"]
|===
| Status | Descrição 


| Instalação | O operador está instalando Trident usando este  `TridentOrchestrator` CR. 


| Instalado | Trident foi instalado com sucesso. 


| Desinstalando | O operador está desinstalando Trident porque 
`spec.uninstall=true`. 


| Desinstalado | Trident foi desinstalado. 


| Falha | O operador não conseguiu instalar, corrigir, atualizar ou desinstalar Trident; o operador tentará recuperar-se automaticamente deste estado. Se este estado persistir, será necessário realizar a resolução de problemas. 


| Atualizando | O operador está atualizando uma instalação existente. 


| Erro | O  `TridentOrchestrator` não é usado. Já existe outro. 
|===


=== Usando o status de criação do pod

Você pode confirmar se a instalação do Trident foi concluída verificando o status dos pods criados:

[listing]
----
kubectl get pods -n trident

NAME                                       READY   STATUS    RESTARTS   AGE
trident-controller-7d466bf5c7-v4cpw        6/6     Running   0           1m
trident-node-linux-mr6zc                   2/2     Running   0           1m
trident-node-linux-xrp7w                   2/2     Running   0           1m
trident-node-linux-zh2jt                   2/2     Running   0           1m
trident-operator-766f7b8658-ldzsv          1/1     Running   0           3m
----


=== Usando `tridentctl`

Você pode usar  `tridentctl` para verificar a versão do Trident instalada.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.10.0        | 25.10.0        |
+----------------+----------------+
----