---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-operator.html 
keywords: deploy, Trident, methods, operator, tridentctl, registry, registries 
summary: VocĂȘ pode implantar manualmente o operador Trident para instalar o Trident. Esse processo se aplica a instalaĂ§Ă”es em que as imagens de contĂȘiner necessĂĄrias para o Trident nĂŁo estĂŁo armazenadas em um registro privado. 
---
= Implante manualmente o operador Trident (modo padrĂŁo)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VocĂȘ pode implantar manualmente o operador Trident para instalar o Trident. Esse processo se aplica a instalaĂ§Ă”es em que as imagens de contĂȘiner necessĂĄrias para o Trident nĂŁo estĂŁo armazenadas em um registro privado. Se vocĂȘ tiver um registro de imagens privado, use o link:kubernetes-deploy-operator-mirror.html["processo para implantaĂ§ĂŁo offline"].



== InformaĂ§Ă”es crĂ­ticas sobre Trident 25.10

*VocĂȘ deve ler as seguintes informaĂ§Ă”es crĂ­ticas sobre Trident.*

.<strong>InformaĂ§Ă”es crĂ­ticas sobre Trident</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 agora Ă© compatĂ­vel com Trident. Atualize Trident antes de atualizar Kubernetes.
* Trident impĂ”e rigorosamente o uso da configuraĂ§ĂŁo de multipath em ambientes SAN, com um valor recomendado de  `find_multipaths: no` no arquivo multipath.conf.
+
O uso de configuraĂ§ĂŁo sem multipath ou o uso de  `find_multipaths: yes` ou  `find_multipaths: smart` valor no arquivo multipath.conf resultarĂĄ em falhas de montagem. Trident recomenda o uso de  `find_multipaths: no` desde o lanĂ§amento 21.07.



=====
====


== Implante manualmente o operador Trident e instale o Trident

Revise link:../trident-get-started/kubernetes-deploy.html["visĂŁo geral da instalaĂ§ĂŁo"] para garantir que vocĂȘ atendeu aos prĂ©-requisitos de instalaĂ§ĂŁo e selecionou a opĂ§ĂŁo de instalaĂ§ĂŁo correta para o seu ambiente.

.Antes de comeĂ§ar
Antes de iniciar a instalaĂ§ĂŁo, faĂ§a login no host Linux e verifique se ele estĂĄ gerenciando um sistema operacional em funcionamento link:requirements.html["cluster Kubernetes suportado"^] e se vocĂȘ possui os privilĂ©gios necessĂĄrios.


NOTE: Com OpenShift, use  `oc` em vez de  `kubectl` em todos os exemplos a seguir e faĂ§a login como *system:admin* primeiro executando  `oc login -u system:admin` ou  `oc login -u kube-admin`.

[%collapsible%open]
====
. Verifique sua versĂŁo do Kubernetes:
+
[listing]
----
kubectl version
----
. Verifique privilĂ©gios de administrador do cluster:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Verifique se vocĂȘ consegue iniciar um pod que utiliza uma imagem do Docker Hub e acessar seu sistema de storage pela rede de pods:
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


=== Passo 1: Baixe o pacote de instalaĂ§ĂŁo do Trident

O pacote de instalaĂ§ĂŁo do Trident contĂ©m tudo o que vocĂȘ precisa para implantar o operador Trident e instalar o Trident. Baixe e extraia a versĂŁo mais recente do instalador do Trident em link:https://github.com/NetApp/trident/releases/latest["a seĂ§ĂŁo _Ativos_ em GitHub"^].

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v25.10.0/trident-installer-25.10.0.tar.gz
tar -xf trident-installer-25.10.0.tar.gz
cd trident-installer
----


=== Etapa 2: criar o  `TridentOrchestrator`CRD

Crie a `TridentOrchestrator` DefiniĂ§ĂŁo de Recurso Personalizado (CRD). VocĂȘ criarĂĄ um `TridentOrchestrator` Recurso Personalizado posteriormente. Use a versĂŁo YAML apropriada da CRD em `deploy/crds` para criar a `TridentOrchestrator` CRD.

[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----


=== Etapa 3: implante o operador Trident

O instalador do Trident fornece um arquivo de pacote que pode ser usado para instalar o operador e criar objetos associados. O arquivo de pacote Ă© uma maneira fĂĄcil de implantar o operador e instalar Trident usando uma configuraĂ§ĂŁo padrĂŁo.

* Para clusters executando Kubernetes 1.24, use `bundle_pre_1_25.yaml`.
* Para clusters executando Kubernetes 1.25 ou posterior, use `bundle_post_1_25.yaml`.


.Antes de comeĂ§ar
* Por padrĂŁo, o instalador do Trident implanta o operador no  `trident` namespace. Se o  `trident` namespace nĂŁo existir, crie-o usando:
+
[listing]
----
kubectl apply -f deploy/namespace.yaml
----
* Para implantar o operador em um namespace diferente do `trident` namespace, atualize `serviceaccount.yaml`, `clusterrolebinding.yaml` e `operator.yaml` e gere seu arquivo de pacote usando o `kustomization.yaml`.
+
.. Crie o  `kustomization.yaml` usando o seguinte comando onde _<bundle.yaml>_ Ă©  `bundle_pre_1_25.yaml` ou  `bundle_post_1_25.yaml` com base na sua versĂŁo do Kubernetes.
+
[listing]
----
cp deploy/kustomization_<bundle.yaml> deploy/kustomization.yaml
----
.. Compile o pacote usando o seguinte comando, onde _<bundle.yaml>_ Ă©  `bundle_pre_1_25.yaml` ou  `bundle_post_1_25.yaml` com base na sua versĂŁo do Kubernetes.
+
[listing]
----
kubectl kustomize deploy/ > deploy/<bundle.yaml>
----




.Passos
. Crie os recursos e implemente o operador:
+
[listing]
----
kubectl create -f deploy/<bundle.yaml>
----
. Verifique se o operador, a implantaĂ§ĂŁo e os replicasets foram criados.
+
[listing]
----
kubectl get all -n <operator-namespace>
----



IMPORTANT: Deve haver apenas *uma instĂąncia* do operador em um cluster Kubernetes. NĂŁo crie vĂĄrias implantaĂ§Ă”es do operador Trident.



=== Passo 4: Crie o `TridentOrchestrator` e instale Trident

Agora vocĂȘ pode criar o `TridentOrchestrator` e instalar Trident. Opcionalmente, vocĂȘ pode link:kubernetes-customize-deploy.html["Personalize a sua instalaĂ§ĂŁo do Trident"] usando os atributos na `TridentOrchestrator` spec.

[listing]
----
kubectl create -f deploy/crds/tridentorchestrator_cr.yaml
tridentorchestrator.trident.netapp.io/trident created

kubectl describe torc trident

Name:        trident
Namespace:
Labels:      <none>
Annotations: <none>
API Version: trident.netapp.io/v1
Kind:        TridentOrchestrator
...
Spec:
  Debug:     true
  Namespace: trident
  nodePrep:
  - iscsi
Status:
  Current Installation Params:
    IPv6:                      false
    Autosupport Hostname:
    Autosupport Image:         netapp/trident-autosupport:25.10
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                     true
    Image Pull Secrets:
    Image Registry:
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Silence Autosupport:  false
    Trident Image:        netapp/trident:25.10.0
  Message:                  Trident installed  Namespace:                trident
  Status:                   Installed
  Version:                  v25.10.0
Events:
    Type Reason Age From Message ---- ------ ---- ---- -------Normal
    Installing 74s trident-operator.netapp.io Installing Trident Normal
    Installed 67s trident-operator.netapp.io Trident installed
----


== Verifique a instalaĂ§ĂŁo

Existem vĂĄrias maneiras de verificar sua instalaĂ§ĂŁo.



=== Usando  `TridentOrchestrator` status

O status de `TridentOrchestrator` indica se a instalaĂ§ĂŁo foi bem-sucedida e exibe a versĂŁo do Trident instalada. Durante a instalaĂ§ĂŁo, o status de `TridentOrchestrator` muda de `Installing` para `Installed`. Se vocĂȘ observar o status de `Failed` e o operador nĂŁo conseguir se recuperar sozinho, link:../troubleshooting.html["verifique os logs"].

[cols="2"]
|===
| Status | DescriĂ§ĂŁo 


| InstalaĂ§ĂŁo | O operador estĂĄ instalando Trident usando este  `TridentOrchestrator` CR. 


| Instalado | Trident foi instalado com sucesso. 


| Desinstalando | O operador estĂĄ desinstalando Trident porque 
`spec.uninstall=true`. 


| Desinstalado | Trident foi desinstalado. 


| Falha | O operador nĂŁo conseguiu instalar, corrigir, atualizar ou desinstalar Trident; o operador tentarĂĄ recuperar-se automaticamente deste estado. Se este estado persistir, serĂĄ necessĂĄrio realizar a resoluĂ§ĂŁo de problemas. 


| Atualizando | O operador estĂĄ atualizando uma instalaĂ§ĂŁo existente. 


| Erro | O  `TridentOrchestrator` nĂŁo Ă© usado. JĂĄ existe outro. 
|===


=== Usando o status de criaĂ§ĂŁo do pod

VocĂȘ pode confirmar se a instalaĂ§ĂŁo do Trident foi concluĂ­da verificando o status dos pods criados:

[listing]
----
kubectl get pods -n trident

NAME                                       READY   STATUS    RESTARTS   AGE
trident-controller-7d466bf5c7-v4cpw        6/6     Running   0           1m
trident-node-linux-mr6zc                   2/2     Running   0           1m
trident-node-linux-xrp7w                   2/2     Running   0           1m
trident-node-linux-zh2jt                   2/2     Running   0           1m
trident-operator-766f7b8658-ldzsv          1/1     Running   0           3m
----


=== Usando `tridentctl`

VocĂȘ pode usar  `tridentctl` para verificar a versĂŁo do Trident instalada.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.10.0        | 25.10.0        |
+----------------+----------------+
----