---
sidebar: sidebar 
permalink: trident-get-started/k8s-netapp.html 
keywords: kubernetes, netapp storage, ontap, cloud volumes ontap, santricity, element software, netapp hci, anf, azure netapp files, aws, amazon fsx 
summary: O portfólio de produtos de storage da NetApp integra-se a diversos aspectos de um cluster Kubernetes, oferecendo recursos avançados de gerenciamento de dados que aprimoram a funcionalidade, a capacidade, o desempenho e a disponibilidade da implementação do Kubernetes. 
---
= Integração do Kubernetes com produtos NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O portfólio de produtos de storage da NetApp integra-se a diversos aspectos de um cluster Kubernetes, oferecendo recursos avançados de gerenciamento de dados que aprimoram a funcionalidade, a capacidade, o desempenho e a disponibilidade da implementação do Kubernetes.



== Trident

https://docs.netapp.com/us-en/trident/["Trident"^] facilita para as empresas o gerenciamento, a proteção e a movimentação de suas cargas de trabalho conteinerizadas ricas em dados, executadas no Kubernetes dentro e entre nuvens públicas e ambientes locais. Trident provisiona e fornece armazenamento persistente para contêineres usando Trident do comprovado e abrangente portfólio de storage NetApp na nuvem pública e em ambientes locais. Ele também oferece um conjunto robusto de funcionalidades avançadas de gerenciamento de dados com reconhecimento de aplicativos, como snapshot, backup e restauração, logs de atividades e clonagem ativa para proteção de dados, recuperação de dados, auditoria de dados e casos de uso de migração para cargas de trabalho do Kubernetes.



== ONTAP

ONTAP é o sistema operacional de storage unificado multiprotocolo da NetApp que oferece recursos avançados de gerenciamento de dados para qualquer aplicação. Os sistemas ONTAP possuem configurações all-flash, híbridas ou totalmente em HDD e oferecem diversos modelos de implementação, incluindo hardware projetado (FAS e AFF), white-box (ONTAP Select) e somente em nuvem (Cloud Volumes ONTAP).


NOTE: Trident é compatível com todos os modelos de implantação ONTAP mencionados acima.



== Cloud Volumes ONTAP

http://cloud.netapp.com/ontap-cloud?utm_source=GitHub&utm_campaign=Trident["Cloud Volumes ONTAP"^] é um dispositivo de storage somente de software que executa o software de gerenciamento de dados ONTAP na nuvem. Você pode usar Cloud Volumes ONTAP para cargas de trabalho de produção, recuperação de desastres, DevOps, serviço de compartilhamento de arquivos e gerenciamento de banco de dados. Ele estende o storage corporativo para a nuvem, oferecendo eficiências de storage, alta disponibilidade, replicação de dados, tiering de dados e consistência de aplicativos.



== Amazon FSx for NetApp ONTAP

https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP"^] é um serviço totalmente gerenciado da AWS que permite que você inicie e execute sistemas de arquivos alimentados pelo sistema operacional de storage NetApp ONTAP. FSx for ONTAP permite que você aproveite os recursos, desempenho e capacidades administrativas do NetApp com os quais você já está familiarizado, enquanto aproveita a simplicidade, agilidade, segurança e escalabilidade de armazenar dados na AWS. FSx for ONTAP oferece suporte a muitos dos recursos do sistema de arquivos ONTAP e APIs de administração.



== Software Element

https://www.netapp.com/data-management/element-software/["Elemento"^] permite ao administrador de storage consolidar cargas de trabalho, garantindo desempenho e possibilitando uma infraestrutura de storage simplificada e otimizada. Em conjunto com uma API que permite a automação de todos os aspectos do gerenciamento de storage, Element possibilita que os administradores de storage façam mais com menos esforço.



== NetApp HCI

https://www.netapp.com/virtual-desktop-infrastructure/netapp-hci/["NetApp HCI"^] simplifica a gestão e a escalabilidade do centro de dados ao automatizar tarefas rotineiras e permitir que os administradores de infraestrutura se concentrem em funções mais importantes.

NetApp HCI é totalmente compatível com Trident. Trident pode provisionar e gerenciar dispositivos de storage para aplicações em contêineres diretamente na plataforma de storage NetApp HCI.



== Azure NetApp Files

https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files"^] é um serviço de compartilhamento de arquivos do Azure de nível empresarial, desenvolvido com tecnologia NetApp. Você pode executar suas cargas de trabalho baseadas em arquivos mais exigentes nativamente no Azure, com o desempenho e o gerenciamento de rich data que você espera da NetApp.



== Google Cloud NetApp Volumes

https://cloud.netapp.com/cloud-volumes-service-for-gcp?utm_source=GitHub&utm_campaign=Trident["Google Cloud NetApp Volumes"^] é um serviço de arquivos nativo da nuvem que fornece volumes NAS sobre NFS com desempenho all-flash. Esse serviço permite que qualquer carga de trabalho, incluindo aplicativos legados, seja executada na nuvem do GCP. Ele oferece um serviço totalmente gerenciado que proporciona alto desempenho consistente, clonagem instantânea, proteção de dados e acesso seguro a instâncias do Google Compute Engine (GCE).
