---
sidebar: sidebar 
permalink: trident-reco/deploy-reco.html 
keywords: deployment, deploy, trident, namespace 
summary: Use as recomendações listadas aqui ao implantar Trident. 
---
= Implantação
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use as recomendações listadas aqui ao implantar Trident.



== Implantar em um namespace dedicado

https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/["Espaços de nomes"^] fornecem separação administrativa entre diferentes aplicações e são uma barreira para o compartilhamento de recursos. Por exemplo, um PVC de um namespace não pode ser consumido por outro. Trident fornece recursos de PV para todos os namespaces no cluster Kubernetes e, consequentemente, utiliza uma conta de serviço que possui privilégios elevados.

Além disso, o acesso ao Trident pod pode permitir que um usuário acesse as credenciais do sistema de storage e outras informações confidenciais. É importante garantir que os usuários do aplicativo e os aplicativos de gerenciamento não tenham a capacidade de acessar as definições de objeto do Trident ou os próprios pods.



== Utilize quotas e limites de intervalo para controlar o consumo de armazenamento

O Kubernetes possui dois recursos que, quando combinados, fornecem um mecanismo poderoso para limitar o consumo de recursos por aplicativos. O https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota["mecanismo de cota de armazenamento"^] permite que o administrador implemente limites globais e específicos de classe de armazenamento para capacidade e contagem de objetos por namespace. Além disso, usar um https://kubernetes.io/docs/tasks/administer-cluster/limit-storage-consumption/#limitrange-to-limit-requests-for-storage["limite de intervalo"^] garante que as solicitações de PVC estejam dentro de um valor mínimo e máximo antes de serem encaminhadas ao provisionador.

Esses valores são definidos para cada namespace individualmente, o que significa que cada namespace deve ter valores definidos que estejam de acordo com seus requisitos de recursos. Veja aqui para informações sobre  https://netapp.io/2017/06/09/self-provisioning-storage-kubernetes-without-worry["como aproveitar quotas"^].
