---
sidebar: sidebar 
permalink: trident-protect/learn-about-trident-protect.html 
keywords: overview, concepts, features, use case, workloads, how workload factory works 
summary: Trident Protect permite que você proteja seus aplicativos e dados de aplicativos usando Trident. 
---
= Saiba mais sobre Trident Protect
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Trident Protect oferece recursos avançados de gerenciamento de dados de aplicativos que aprimoram a funcionalidade e a disponibilidade de aplicativos Kubernetes com estado, com suporte dos sistemas de armazenamento NetApp ONTAP e do provisionador de armazenamento NetApp Trident CSI. Trident Protect simplifica o gerenciamento, a proteção e a movimentação de cargas de trabalho conteinerizadas em nuvens públicas e ambientes locais. Ele também oferece recursos de automação por meio de sua API e CLI.

Você pode proteger aplicativos com Trident Protect criando recursos personalizados (CRs) ou usando a Trident Protect CLI.



== Qual é o próximo passo?

Você pode conhecer os requisitos do Trident Protect antes de instalá-lo:

* link:trident-protect-requirements.html["Requisitos do Trident Protect"]

