---
sidebar: sidebar 
permalink: trident-protect/trident-protect-restore-settings.html 
keywords: trident, protect, restore, data, backup 
summary: Você pode personalizar as operações de restauração do Trident Protect usando anotações, configurações de namespace e opções de armazenamento. 
---
= Use as configurações avançadas de restauração do Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode personalizar as operações de restauração usando configurações avançadas, como anotações, configurações de namespace e opções de armazenamento para atender às suas necessidades específicas.



== Anotações e rótulos de namespace durante operações de restauração e failover

Durante as operações de restauração e failover, os rótulos e anotações no namespace de destino são ajustados para corresponder aos rótulos e anotações no namespace de origem. Rótulos ou anotações do namespace de origem que não existem no namespace de destino são adicionados, e quaisquer rótulos ou anotações já existentes são sobrescritos para corresponder ao valor do namespace de origem. Rótulos ou anotações que existem apenas no namespace de destino permanecem inalterados.


NOTE: Se você usa Red Hat OpenShift, é importante observar o papel crucial das anotações de namespace em ambientes OpenShift. As anotações de namespace garantem que os pods restaurados sigam as permissões e configurações de segurança apropriadas definidas pelas restrições de contexto de segurança (SCCs) do OpenShift e possam acessar volumes sem problemas de permissão. Para mais informações, consulte o link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["OpenShift security context constraints documentação"^].

Você pode impedir que anotações específicas no namespace de destino sejam sobrescritas definindo a variável de ambiente do Kubernetes  `RESTORE_SKIP_NAMESPACE_ANNOTATIONS` antes de executar a operação de restauração ou failover. Por exemplo:

[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set-string restoreSkipNamespaceAnnotations="{<annotation_key_to_skip_1>,<annotation_key_to_skip_2>}" \
  --reuse-values
----

NOTE: Ao executar uma operação de restauração ou failover, quaisquer anotações e rótulos de namespace especificados em  `restoreSkipNamespaceAnnotations` e  `restoreSkipNamespaceLabels` são excluídos da operação de restauração ou failover. Certifique-se de que essas configurações sejam definidas durante a instalação inicial do Helm. Para saber mais, consulte link:../trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Configurar configurações adicionais do helm chart do Trident Protect"].

Se você instalou o aplicativo de origem usando Helm com a  `--create-namespace` flag, um tratamento especial é dado à chave de rótulo  `name`. Durante o processo de restauração ou failover, Trident Protect copia esse rótulo para o namespace de destino, mas atualiza o valor para o valor do namespace de destino se o valor da origem corresponder ao namespace de origem. Se esse valor não corresponder ao namespace de origem, ele é copiado para o namespace de destino sem alterações.



=== Exemplo

O exemplo a seguir apresenta um namespace de origem e um de destino, cada um com anotações e rótulos diferentes. Você pode ver o estado do namespace de destino antes e depois da operação, e como as anotações e os rótulos são combinados ou sobrescritos no namespace de destino.



==== Antes da operação de restauração ou failover

A tabela a seguir ilustra o estado dos namespaces de origem e destino do exemplo antes da operação de restauração ou failover:

[cols="1,2a,2a"]
|===
| Espaço de nomes | Anotações | Etiquetas 


| Namespace ns-1 (fonte)  a| 
* annotation.one/key: "valoratualizado"
* anotação.dois/chave: "true"

 a| 
* ambiente=produção
* compliance=hipaa
* name=ns-1




| Espaço de nomes ns-2 (destino)  a| 
* annotation.one/key: "true"
* anotação.three/chave: "falso"

 a| 
* role=database


|===


==== Após a operação de restauração

A tabela a seguir ilustra o estado do namespace de destino de exemplo após a operação de restauração ou failover. Algumas chaves foram adicionadas, outras foram sobrescritas e o  `name` rótulo foi atualizado para corresponder ao namespace de destino:

[cols="1,2a,2a"]
|===
| Espaço de nomes | Anotações | Etiquetas 


| Espaço de nomes ns-2 (destino)  a| 
* annotation.one/key: "valoratualizado"
* anotação.dois/chave: "true"
* anotação.three/chave: "falso"

 a| 
* name=ns-2
* compliance=hipaa
* ambiente=produção
* role=database


|===


== Campos suportados

Esta seção descreve os campos adicionais disponíveis para operações de restauração.



=== Mapeamento de classe de armazenamento

O  `spec.storageClassMapping` atributo define um mapeamento de uma classe de armazenamento presente na aplicação de origem para uma nova classe de armazenamento no cluster de destino. Você pode usar isso ao migrar aplicações entre clusters com classes de armazenamento diferentes ou ao alterar o backend de armazenamento para operações de BackupRestore.

*Exemplo:*

[source, yaml]
----
storageClassMapping:
  - destination: "destinationStorageClass1"
    source: "sourceStorageClass1"
  - destination: "destinationStorageClass2"
    source: "sourceStorageClass2"
----


== Anotações suportadas

Esta seção lista as anotações suportadas para configurar diversos comportamentos no sistema. Se uma anotação não for definida explicitamente pelo usuário, o sistema usará o valor padrão.

[cols="1,1,3,1"]
|===
| Anotação | Tipo | Descrição | Valor padrão 


| protect.trident.netapp.io/data-mover-timeout-sec | string | O tempo máximo (em segundos) permitido para a operação de movimentação de dados ficar parada. | "300" 


| protect.trident.netapp.io/kopia-content-cache-size-limit-mb | string | O limite máximo de tamanho (em megabytes) para o cache de conteúdo do Kopia. | "1000" 


| protect.trident.netapp.io/pvc-bind-timeout-sec | string | Tempo máximo (em segundos) de espera para que qualquer PersistentVolumeClaims (PVC) recém-criado atinja a  `Bound` fase antes que a operação falhe. Aplica-se a todos os tipos de CR de restauração (BackupRestore, BackupInplaceRestore, SnapshotRestore, SnapshotInplaceRestore). Use um valor maior se o seu backend de armazenamento ou cluster exigir mais tempo com frequência. | "1200" (20 minutos) 
|===